package com.Harbinger.Spore.Core;

import com.Harbinger.Spore.Sblocks.Acid;
import com.Harbinger.Spore.Sblocks.BileLiquidBlock;
import com.Harbinger.Spore.Sblocks.BileLump;
import com.Harbinger.Spore.Sblocks.BiomassBulb;
import com.Harbinger.Spore.Sblocks.BiomassLump;
import com.Harbinger.Spore.Sblocks.BrainRemnants;
import com.Harbinger.Spore.Sblocks.Branch;
import com.Harbinger.Spore.Sblocks.CDUBlock;
import com.Harbinger.Spore.Sblocks.Cabinet;
import com.Harbinger.Spore.Sblocks.CancerLungs;
import com.Harbinger.Spore.Sblocks.Cerebrum;
import com.Harbinger.Spore.Sblocks.Container;
import com.Harbinger.Spore.Sblocks.CookedTorsoBlock;
import com.Harbinger.Spore.Sblocks.CorrosiveDrownedLump;
import com.Harbinger.Spore.Sblocks.CrustedBile;
import com.Harbinger.Spore.Sblocks.DrownedLump;
import com.Harbinger.Spore.Sblocks.ExplodingLump;
import com.Harbinger.Spore.Sblocks.FallingAcidSack;
import com.Harbinger.Spore.Sblocks.FangLump;
import com.Harbinger.Spore.Sblocks.FlamableRotatingBlock;
import com.Harbinger.Spore.Sblocks.FrozenBiomass;
import com.Harbinger.Spore.Sblocks.FrozenRemains;
import com.Harbinger.Spore.Sblocks.FungalClamp;
import com.Harbinger.Spore.Sblocks.FungalCrops;
import com.Harbinger.Spore.Sblocks.FungalSaplings;
import com.Harbinger.Spore.Sblocks.FungalStem;
import com.Harbinger.Spore.Sblocks.FungalStemTop;
import com.Harbinger.Spore.Sblocks.GastricBiomassBlock;
import com.Harbinger.Spore.Sblocks.GenericFoliageBlock;
import com.Harbinger.Spore.Sblocks.Hand;
import com.Harbinger.Spore.Sblocks.HangingGlowShroom;
import com.Harbinger.Spore.Sblocks.HangingPlant;
import com.Harbinger.Spore.Sblocks.HangingPlantBub;
import com.Harbinger.Spore.Sblocks.HangingRoots;
import com.Harbinger.Spore.Sblocks.HangingStem;
import com.Harbinger.Spore.Sblocks.HeartPie;
import com.Harbinger.Spore.Sblocks.HiveSpawn;
import com.Harbinger.Spore.Sblocks.IncubatorBlock;
import com.Harbinger.Spore.Sblocks.IronLadderBlock;
import com.Harbinger.Spore.Sblocks.LabBedBlock;
import com.Harbinger.Spore.Sblocks.MembraneBlock;
import com.Harbinger.Spore.Sblocks.MyceliumVeins;
import com.Harbinger.Spore.Sblocks.OrganiteBlock;
import com.Harbinger.Spore.Sblocks.OutpostWatcher;
import com.Harbinger.Spore.Sblocks.OvergrownSpawner;
import com.Harbinger.Spore.Sblocks.Remains;
import com.Harbinger.Spore.Sblocks.RottenBush;
import com.Harbinger.Spore.Sblocks.SelectableBlock;
import com.Harbinger.Spore.Sblocks.SelectableFallingBlock;
import com.Harbinger.Spore.Sblocks.SickenBiomassBlock;
import com.Harbinger.Spore.Sblocks.SkullSoupBlock;
import com.Harbinger.Spore.Sblocks.SurgeryTableBlock;
import com.Harbinger.Spore.Sblocks.UnderWaterFungalStem;
import com.Harbinger.Spore.Sblocks.UnderWaterFungusTop;
import com.Harbinger.Spore.Sblocks.VentPlateBlock;
import com.Harbinger.Spore.Sblocks.WallFolliage;
import com.Harbinger.Spore.Sblocks.WallRemainsBlock;
import com.Harbinger.Spore.Sblocks.WallVocalsBlock;
import com.Harbinger.Spore.Sblocks.WoodenScraps;
import com.Harbinger.Spore.Sblocks.ZoaholicBlock;
import com.Harbinger.Spore.Sblocks.Lights.BrokenHalogenLight;
import com.Harbinger.Spore.Sblocks.Lights.BrokenHalogenLightOn;
import com.Harbinger.Spore.Sblocks.Lights.HalogenLight;
import com.Harbinger.Spore.Sblocks.Lights.HalogenLightOn;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class Sblocks {
   public static final DeferredRegister BLOCKS;
   public static final RegistryObject ACID;
   public static final RegistryObject CONTAINER;
   public static final RegistryObject LAB_BLOCK;
   public static final RegistryObject LAB_BLOCK1;
   public static final RegistryObject LAB_BLOCK2;
   public static final RegistryObject LAB_BLOCK3;
   public static final RegistryObject LAB_SLAB;
   public static final RegistryObject LAB_SLAB1;
   public static final RegistryObject LAB_SLAB2;
   public static final RegistryObject LAB_SLAB3;
   public static final RegistryObject LAB_STAIR;
   public static final RegistryObject IRON_LADDER;
   public static final RegistryObject VENT_PLATE;
   public static final RegistryObject RUSTED_VENT_PLATE;
   public static final RegistryObject VENT_DOOR;
   public static final RegistryObject CDU;
   public static final RegistryObject ZOAHOLIC;
   public static final RegistryObject INCUBATOR;
   public static final RegistryObject SURGERY_TABLE;
   public static final RegistryObject CABINET;
   public static final RegistryObject REINFORCED_DOOR;
   public static final RegistryObject RUSTED_REINFORCED_DOOR;
   public static final RegistryObject FROZEN_REINFORCED_DOOR;
   public static final RegistryObject GROWTHS_BIG;
   public static final RegistryObject GROWTHS_SMALL;
   public static final RegistryObject FUNGAL_STEM_SAPLING;
   public static final RegistryObject BLOOM_G;
   public static final RegistryObject BLOOM_GG;
   public static final RegistryObject FUNGAL_STEM;
   public static final RegistryObject UNDERWATER_FUNGAL_STEM;
   public static final RegistryObject HANGING_FUNGAL_STEM;
   public static final RegistryObject FUNGAL_STEM_TOP;
   public static final RegistryObject UNDERWATER_FUNGAL_STEM_TOP;
   public static final RegistryObject FUNGAL_ROOTS;
   public static final RegistryObject ACIDIC_SACK;
   public static final RegistryObject HAND;
   public static final RegistryObject LUNGS;
   public static final RegistryObject GLOWSHROOM;
   public static final RegistryObject GROWTH_MYCELIUM;
   public static final RegistryObject WALL_GROWTHS;
   public static final RegistryObject WALL_GROWTHS_BIG;
   public static final RegistryObject WALL_GROWTHS_FLESHY;
   public static final RegistryObject VOCALS;
   public static final RegistryObject MYCELIUM_VEINS;
   public static final RegistryObject BIOMASS_BULB;
   public static final RegistryObject EXPLODING_LUMP;
   public static final RegistryObject POISONING_LUMP;
   public static final RegistryObject INFESTED_DIRT;
   public static final RegistryObject INFESTED_STONE;
   public static final RegistryObject INFESTED_NETHERRACK;
   public static final RegistryObject INFESTED_SOUL_SAND;
   public static final RegistryObject INFESTED_END_STONE;
   public static final RegistryObject INFESTED_SAND;
   public static final RegistryObject INFESTED_GRAVEL;
   public static final RegistryObject INFESTED_DEEPSLATE;
   public static final RegistryObject INFESTED_RED_SAND;
   public static final RegistryObject INFESTED_CLAY;
   public static final RegistryObject INFESTED_COBBLESTONE;
   public static final RegistryObject INFESTED_COBBLED_DEEPSLATE;
   public static final RegistryObject INFESTED_STONE_BRICKS;
   public static final RegistryObject INFESTED_BRICKS;
   public static final RegistryObject INFESTED_LABORATORY_BLOCK;
   public static final RegistryObject INFESTED_LABORATORY_BLOCK1;
   public static final RegistryObject INFESTED_LABORATORY_BLOCK2;
   public static final RegistryObject INFESTED_LABORATORY_BLOCK3;
   public static final RegistryObject OVERGROWN_SPAWNER;
   public static final RegistryObject BRAIN_REMNANTS;
   public static final RegistryObject OUTPOST_WATCHER;
   public static final RegistryObject SKULL_SOUP;
   public static final RegistryObject HEART_PIE;
   public static final RegistryObject COOKED_TORSO;
   public static final RegistryObject ROTTEN_LOG;
   public static final RegistryObject ROTTEN_PLANKS;
   public static final RegistryObject ROTTEN_STAIR;
   public static final RegistryObject ROTTEN_SLAB;
   public static final RegistryObject ROTTEN_SCRAPS;
   public static final RegistryObject ROTTEN_BRANCH;
   public static final RegistryObject ROTTEN_BUSH;
   public static final RegistryObject ROTTEN_GRASS;
   public static final RegistryObject ROTTEN_FERN;
   public static final RegistryObject ROTTEN_CROPS;
   public static final RegistryObject BIOMASS_LUMP;
   public static final RegistryObject HIVE_SPAWN;
   public static final RegistryObject LABORATORY_BED;
   public static final RegistryObject ORGANITE;
   public static final RegistryObject ROOTED_BIOMASS;
   public static final RegistryObject BIOMASS_BLOCK;
   public static final RegistryObject SICKEN_BIOMASS_BLOCK;
   public static final RegistryObject GASTRIC_BIOMASS;
   public static final RegistryObject CALCIFIED_BIOMASS_BLOCK;
   public static final RegistryObject MEMBRANE_BLOCK;
   public static final RegistryObject ROOTED_MYCELIUM;
   public static final RegistryObject FUNGAL_SHELL;
   public static final RegistryObject MYCELIUM_BLOCK;
   public static final RegistryObject MYCELIUM_SLAB;
   public static final RegistryObject FROST_BURNED_BIOMASS;
   public static final RegistryObject BILE;
   public static final RegistryObject CRUSTED_BILE;
   public static final RegistryObject REMAINS;
   public static final RegistryObject WALL_REMAINS;
   public static final RegistryObject FROZEN_REMAINS;
   public static final RegistryObject CEREBRUM_BLOCK;
   public static final RegistryObject INNARDS_BLOCK;
   public static final RegistryObject HEART_BLOCK;
   public static final RegistryObject BRAIO_BLOCK;
   public static final RegistryObject DROWNED_LUMP;
   public static final RegistryObject BILE_LUMP;
   public static final RegistryObject FANG_LUMP;
   public static final RegistryObject FUNGAL_CLAMP;
   public static final RegistryObject HALOGEN_LIGHT;
   public static final RegistryObject HALOGEN_LIGHT_ON;
   public static final RegistryObject BROKEN_HALOGEN_LIGHT;
   public static final RegistryObject BROKEN_HALOGEN_LIGHT_ON;

   public static void register(IEventBus eventBus) {
      BLOCKS.register(eventBus);
   }

   static {
      BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, "spore");
      ACID = BLOCKS.register("acid", Acid::new);
      CONTAINER = BLOCKS.register("container", Container::new);
      LAB_BLOCK = BLOCKS.register("lab_block", () -> new Block(Properties.of().sound(SoundType.STONE).strength(6.0F, 20.0F)));
      LAB_BLOCK1 = BLOCKS.register("lab_block1", () -> new Block(Properties.of().sound(SoundType.STONE).strength(6.0F, 20.0F)));
      LAB_BLOCK2 = BLOCKS.register("lab_block2", () -> new Block(Properties.of().sound(SoundType.STONE).strength(6.0F, 20.0F)));
      LAB_BLOCK3 = BLOCKS.register("lab_block3", () -> new Block(Properties.of().sound(SoundType.STONE).strength(6.0F, 20.0F)));
      LAB_SLAB = BLOCKS.register("lab_slab", () -> new SlabBlock(Properties.copy((BlockBehaviour)LAB_BLOCK.get())));
      LAB_SLAB1 = BLOCKS.register("lab_slab1", () -> new SlabBlock(Properties.copy((BlockBehaviour)LAB_BLOCK1.get())));
      LAB_SLAB2 = BLOCKS.register("lab_slab2", () -> new SlabBlock(Properties.copy((BlockBehaviour)LAB_BLOCK2.get())));
      LAB_SLAB3 = BLOCKS.register("lab_slab3", () -> new SlabBlock(Properties.copy((BlockBehaviour)LAB_BLOCK3.get())));
      LAB_STAIR = BLOCKS.register("lab_stair", () -> new StairBlock(() -> ((Block)LAB_BLOCK.get()).defaultBlockState(), Properties.copy((BlockBehaviour)LAB_BLOCK.get())));
      IRON_LADDER = BLOCKS.register("iron_ladder", () -> new IronLadderBlock(Properties.of().sound(SoundType.METAL).strength(2.0F, 4.0F).noOcclusion().sound(SoundType.METAL)));
      VENT_PLATE = BLOCKS.register("vent_plate", VentPlateBlock::new);
      RUSTED_VENT_PLATE = BLOCKS.register("rusted_vent_plate", VentPlateBlock::new);
      VENT_DOOR = BLOCKS.register("vent_door", () -> new TrapDoorBlock(Properties.of().sound(SoundType.METAL).strength(2.0F, 4.0F).noOcclusion().sound(SoundType.METAL), BlockSetType.STONE));
      CDU = BLOCKS.register("cdu", CDUBlock::new);
      ZOAHOLIC = BLOCKS.register("zoaholic", ZoaholicBlock::new);
      INCUBATOR = BLOCKS.register("incubator", IncubatorBlock::new);
      SURGERY_TABLE = BLOCKS.register("surgery_table", SurgeryTableBlock::new);
      CABINET = BLOCKS.register("cabinet", Cabinet::new);
      REINFORCED_DOOR = BLOCKS.register("reinforced_door", () -> new DoorBlock(Properties.of().sound(SoundType.METAL).strength(20.0F, 1200.0F).noOcclusion().sound(SoundType.METAL).noParticlesOnBreak(), BlockSetType.IRON));
      RUSTED_REINFORCED_DOOR = BLOCKS.register("rusted_reinforced_door", () -> new DoorBlock(Properties.of().sound(SoundType.METAL).strength(10.0F, 600.0F).noOcclusion().sound(SoundType.METAL).noParticlesOnBreak(), BlockSetType.IRON));
      FROZEN_REINFORCED_DOOR = BLOCKS.register("frozen_reinforced_door", () -> new DoorBlock(Properties.of().sound(SoundType.METAL).strength(15.0F, 800.0F).noOcclusion().sound(SoundType.METAL).noParticlesOnBreak(), BlockSetType.IRON));
      GROWTHS_BIG = BLOCKS.register("growths_big", () -> new GenericFoliageBlock(Properties.of().sound(SoundType.CROP).strength(0.0F, 0.0F).noCollission().noOcclusion().sound(SoundType.CROP)));
      GROWTHS_SMALL = BLOCKS.register("growths_small", () -> new GenericFoliageBlock(Properties.of().strength(0.0F, 0.0F).noCollission().noOcclusion().sound(SoundType.CROP)));
      FUNGAL_STEM_SAPLING = BLOCKS.register("fungal_stem_sapling", FungalSaplings::new);
      BLOOM_G = BLOCKS.register("blomfung", HangingPlant::new);
      BLOOM_GG = BLOCKS.register("bloomfung2", HangingPlantBub::new);
      FUNGAL_STEM = BLOCKS.register("fungal_stem", FungalStem::new);
      UNDERWATER_FUNGAL_STEM = BLOCKS.register("underwater_fungal_stem", UnderWaterFungalStem::new);
      HANGING_FUNGAL_STEM = BLOCKS.register("hanging_fungal_stem", HangingStem::new);
      FUNGAL_STEM_TOP = BLOCKS.register("fungal_stem_top", FungalStemTop::new);
      UNDERWATER_FUNGAL_STEM_TOP = BLOCKS.register("underwater_fungal_stem_top", UnderWaterFungusTop::new);
      FUNGAL_ROOTS = BLOCKS.register("fungal_roots", HangingRoots::new);
      ACIDIC_SACK = BLOCKS.register("acidic_sack", FallingAcidSack::new);
      HAND = BLOCKS.register("hand", Hand::new);
      LUNGS = BLOCKS.register("lungs", CancerLungs::new);
      GLOWSHROOM = BLOCKS.register("glowshroom", HangingGlowShroom::new);
      GROWTH_MYCELIUM = BLOCKS.register("growth_mycelium", () -> new GenericFoliageBlock(Properties.of().sound(SoundType.CROP).strength(0.0F, 0.0F).noCollission().noOcclusion().sound(SoundType.CROP).lightLevel((s) -> 2).hasPostProcess((bs, br, bp) -> true).emissiveRendering((bs, br, bp) -> true)));
      WALL_GROWTHS = BLOCKS.register("wall_growths", WallFolliage::new);
      WALL_GROWTHS_BIG = BLOCKS.register("wall_growths_big", WallFolliage::new);
      WALL_GROWTHS_FLESHY = BLOCKS.register("wall_growths_fleshy", WallFolliage::new);
      VOCALS = BLOCKS.register("vocals", WallVocalsBlock::new);
      MYCELIUM_VEINS = BLOCKS.register("mycelium_veins", MyceliumVeins::new);
      BIOMASS_BULB = BLOCKS.register("biomass_bulb", BiomassBulb::new);
      EXPLODING_LUMP = BLOCKS.register("exploding_lump", ExplodingLump::new);
      POISONING_LUMP = BLOCKS.register("poisoning_lump", CorrosiveDrownedLump::new);
      INFESTED_DIRT = BLOCKS.register("infested_dirt", () -> new SelectableBlock(Properties.copy(Blocks.COARSE_DIRT)));
      INFESTED_STONE = BLOCKS.register("infested_stone", () -> new SelectableBlock(Properties.copy(Blocks.STONE)));
      INFESTED_NETHERRACK = BLOCKS.register("infested_netherrack", () -> new SelectableBlock(Properties.copy(Blocks.NETHERRACK)));
      INFESTED_SOUL_SAND = BLOCKS.register("infested_soul_sand", () -> new SelectableBlock(Properties.copy(Blocks.SOUL_SAND)));
      INFESTED_END_STONE = BLOCKS.register("infested_end_stone", () -> new SelectableBlock(Properties.copy(Blocks.END_STONE)));
      INFESTED_SAND = BLOCKS.register("infested_sand", () -> new SelectableFallingBlock(Properties.copy(Blocks.SAND)));
      INFESTED_GRAVEL = BLOCKS.register("infested_gravel", () -> new SelectableFallingBlock(Properties.copy(Blocks.GRAVEL)));
      INFESTED_DEEPSLATE = BLOCKS.register("infested_deepslate", () -> new SelectableBlock(Properties.copy(Blocks.DEEPSLATE)));
      INFESTED_RED_SAND = BLOCKS.register("infested_red_sand", () -> new SelectableBlock(Properties.copy(Blocks.RED_SAND)));
      INFESTED_CLAY = BLOCKS.register("infested_clay", () -> new SelectableBlock(Properties.copy(Blocks.CLAY)));
      INFESTED_COBBLESTONE = BLOCKS.register("infested_cobblestone", () -> new SelectableBlock(Properties.copy(Blocks.COBBLESTONE)));
      INFESTED_COBBLED_DEEPSLATE = BLOCKS.register("infested_cobbled_deepslate", () -> new SelectableBlock(Properties.copy(Blocks.COBBLED_DEEPSLATE)));
      INFESTED_STONE_BRICKS = BLOCKS.register("infested_stone_bricks", () -> new SelectableBlock(Properties.copy(Blocks.STONE_BRICKS)));
      INFESTED_BRICKS = BLOCKS.register("infested_bricks", () -> new SelectableBlock(Properties.copy(Blocks.BRICKS)));
      INFESTED_LABORATORY_BLOCK = BLOCKS.register("infested_laboratory_block", () -> new SelectableBlock(Properties.of().sound(SoundType.STONE).strength(3.0F, 10.0F)));
      INFESTED_LABORATORY_BLOCK1 = BLOCKS.register("infested_laboratory_block1", () -> new SelectableBlock(Properties.of().sound(SoundType.STONE).strength(3.0F, 10.0F)));
      INFESTED_LABORATORY_BLOCK2 = BLOCKS.register("infested_laboratory_block2", () -> new SelectableBlock(Properties.of().sound(SoundType.STONE).strength(3.0F, 10.0F)));
      INFESTED_LABORATORY_BLOCK3 = BLOCKS.register("infested_laboratory_block3", () -> new SelectableBlock(Properties.of().sound(SoundType.STONE).strength(3.0F, 10.0F)));
      OVERGROWN_SPAWNER = BLOCKS.register("overgrown_spawner", OvergrownSpawner::new);
      BRAIN_REMNANTS = BLOCKS.register("brain_remnants", BrainRemnants::new);
      OUTPOST_WATCHER = BLOCKS.register("outpost_watcher", OutpostWatcher::new);
      SKULL_SOUP = BLOCKS.register("skull_soup", SkullSoupBlock::new);
      HEART_PIE = BLOCKS.register("heart_pie", HeartPie::new);
      COOKED_TORSO = BLOCKS.register("cooked_torso", CookedTorsoBlock::new);
      ROTTEN_LOG = BLOCKS.register("rotten_log", () -> new FlamableRotatingBlock(Properties.copy(Blocks.OAK_LOG).sound(SoundType.WOOD).randomTicks()));
      ROTTEN_PLANKS = BLOCKS.register("rotten_planks", () -> new Block(Properties.copy(Blocks.OAK_PLANKS).sound(SoundType.WOOD).ignitedByLava()));
      ROTTEN_STAIR = BLOCKS.register("rotten_stair", () -> new StairBlock(((Block)ROTTEN_PLANKS.get()).defaultBlockState(), Properties.copy(Blocks.OAK_PLANKS).sound(SoundType.WOOD).ignitedByLava()));
      ROTTEN_SLAB = BLOCKS.register("rotten_slab", () -> new SlabBlock(Properties.copy(Blocks.OAK_PLANKS).sound(SoundType.WOOD).ignitedByLava()));
      ROTTEN_SCRAPS = BLOCKS.register("rotten_scraps", WoodenScraps::new);
      ROTTEN_BRANCH = BLOCKS.register("rotten_branch", Branch::new);
      ROTTEN_BUSH = BLOCKS.register("rotten_bush", RottenBush::new);
      ROTTEN_GRASS = BLOCKS.register("rotten_grass", RottenBush::new);
      ROTTEN_FERN = BLOCKS.register("rotten_fern", RottenBush::new);
      ROTTEN_CROPS = BLOCKS.register("rotten_crops", FungalCrops::new);
      BIOMASS_LUMP = BLOCKS.register("biomass_lump", BiomassLump::new);
      HIVE_SPAWN = BLOCKS.register("hive_spawn", HiveSpawn::new);
      LABORATORY_BED = BLOCKS.register("laboratory_bed", LabBedBlock::new);
      ORGANITE = BLOCKS.register("organite", OrganiteBlock::new);
      ROOTED_BIOMASS = BLOCKS.register("rooted_biomass", () -> new Block(Properties.of().strength(2.0F, 2.0F).sound(SoundType.SLIME_BLOCK)));
      BIOMASS_BLOCK = BLOCKS.register("biomass_block", () -> new Block(Properties.of().strength(2.0F, 2.0F).sound(SoundType.SLIME_BLOCK)));
      SICKEN_BIOMASS_BLOCK = BLOCKS.register("sicken_biomass_block", () -> new SickenBiomassBlock(Properties.of().strength(4.0F, 4.0F).sound(SoundType.SLIME_BLOCK)));
      GASTRIC_BIOMASS = BLOCKS.register("gastric_biomass_block", () -> new GastricBiomassBlock(Properties.of().strength(4.0F, 4.0F).sound(SoundType.SLIME_BLOCK)));
      CALCIFIED_BIOMASS_BLOCK = BLOCKS.register("calcified_biomass_block", () -> new Block(Properties.of().strength(8.0F, 20.0F).sound(SoundType.SLIME_BLOCK)));
      MEMBRANE_BLOCK = BLOCKS.register("membrane_block", MembraneBlock::new);
      ROOTED_MYCELIUM = BLOCKS.register("rooted_mycelium", () -> new Block(Properties.of().strength(2.0F, 2.0F).sound(SoundType.SLIME_BLOCK)));
      FUNGAL_SHELL = BLOCKS.register("fungal_shell", () -> new Block(Properties.of().strength(20.0F, 6.0F).sound(SoundType.BONE_BLOCK)));
      MYCELIUM_BLOCK = BLOCKS.register("mycelium_block", () -> new RotatedPillarBlock(Properties.of().strength(4.0F, 3.0F).sound(SoundType.BONE_BLOCK)));
      MYCELIUM_SLAB = BLOCKS.register("mycelium_slab", () -> new SlabBlock(Properties.copy((BlockBehaviour)MYCELIUM_BLOCK.get())));
      FROST_BURNED_BIOMASS = BLOCKS.register("freeze_burned_biomass", FrozenBiomass::new);
      BILE = BLOCKS.register("bile", () -> new BileLiquidBlock());
      CRUSTED_BILE = BLOCKS.register("crusted_bile", CrustedBile::new);
      REMAINS = BLOCKS.register("remains", Remains::new);
      WALL_REMAINS = BLOCKS.register("wall_remains", WallRemainsBlock::new);
      FROZEN_REMAINS = BLOCKS.register("frozen_remains", FrozenRemains::new);
      CEREBRUM_BLOCK = BLOCKS.register("cerebrum_block", Cerebrum::new);
      INNARDS_BLOCK = BLOCKS.register("innards_block", Cerebrum::new);
      HEART_BLOCK = BLOCKS.register("heart_block", Cerebrum::new);
      BRAIO_BLOCK = BLOCKS.register("braio_block", Cerebrum::new);
      DROWNED_LUMP = BLOCKS.register("drowned_lump", DrownedLump::new);
      BILE_LUMP = BLOCKS.register("bile_lump", BileLump::new);
      FANG_LUMP = BLOCKS.register("fang_lump", FangLump::new);
      FUNGAL_CLAMP = BLOCKS.register("fungal_clamp", FungalClamp::new);
      HALOGEN_LIGHT = BLOCKS.register("halogen_light", HalogenLight::new);
      HALOGEN_LIGHT_ON = BLOCKS.register("halogen_light_on", HalogenLightOn::new);
      BROKEN_HALOGEN_LIGHT = BLOCKS.register("broken_halogen_light", BrokenHalogenLight::new);
      BROKEN_HALOGEN_LIGHT_ON = BLOCKS.register("broken_halogen_light_on", BrokenHalogenLightOn::new);
   }
}
