package com.Harbinger.Spore.Core;

import com.Harbinger.Spore.Sentities.BaseEntities.HohlMultipart;
import com.Harbinger.Spore.Sentities.BaseEntities.LeviathanMultipart;
import com.Harbinger.Spore.Sentities.BasicInfected.Bairn;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedDiseasedVillager;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedDrowned;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedHazmat;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedHuman;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedHusk;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedPillager;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedPlayer;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedVillager;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedWanderingTrader;
import com.Harbinger.Spore.Sentities.BasicInfected.InfectedWitch;
import com.Harbinger.Spore.Sentities.Calamities.Gazenbrecher;
import com.Harbinger.Spore.Sentities.Calamities.Grakensenker;
import com.Harbinger.Spore.Sentities.Calamities.Hinderburg;
import com.Harbinger.Spore.Sentities.Calamities.Hohlfresser;
import com.Harbinger.Spore.Sentities.Calamities.Howitzer;
import com.Harbinger.Spore.Sentities.Calamities.Leviathan;
import com.Harbinger.Spore.Sentities.Calamities.Sieger;
import com.Harbinger.Spore.Sentities.Calamities.Stahlmorder;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Bloater;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Braionmil;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Brute;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Busser;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Chemist;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Conductor;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Gargoyl;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Gorgon;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Griefer;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Howler;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Inebriator;
import com.Harbinger.Spore.Sentities.EvolvedInfected.InfectedEvoker;
import com.Harbinger.Spore.Sentities.EvolvedInfected.InfectedVendicator;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Jagdhund;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Knight;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Leaper;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Mephetic;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Naiad;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Nuclealave;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Protector;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Scamper;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Scavenger;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Slasher;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Spitter;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Stalker;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Thorn;
import com.Harbinger.Spore.Sentities.EvolvedInfected.Volatile;
import com.Harbinger.Spore.Sentities.Experiments.Biobloob;
import com.Harbinger.Spore.Sentities.Experiments.Lacerator;
import com.Harbinger.Spore.Sentities.Experiments.Plagued;
import com.Harbinger.Spore.Sentities.Experiments.Saugling;
import com.Harbinger.Spore.Sentities.FallenMultipart.HowitzerArm;
import com.Harbinger.Spore.Sentities.FallenMultipart.Licker;
import com.Harbinger.Spore.Sentities.FallenMultipart.SiegerTail;
import com.Harbinger.Spore.Sentities.FallenMultipart.StalhArm;
import com.Harbinger.Spore.Sentities.Hyper.Brot;
import com.Harbinger.Spore.Sentities.Hyper.Grober;
import com.Harbinger.Spore.Sentities.Hyper.Hevoker;
import com.Harbinger.Spore.Sentities.Hyper.Hvindicator;
import com.Harbinger.Spore.Sentities.Hyper.Inquisitor;
import com.Harbinger.Spore.Sentities.Hyper.Ogre;
import com.Harbinger.Spore.Sentities.Hyper.Wendigo;
import com.Harbinger.Spore.Sentities.Organoids.Brauerei;
import com.Harbinger.Spore.Sentities.Organoids.Delusionare;
import com.Harbinger.Spore.Sentities.Organoids.HiveTumor;
import com.Harbinger.Spore.Sentities.Organoids.Mound;
import com.Harbinger.Spore.Sentities.Organoids.Proto;
import com.Harbinger.Spore.Sentities.Organoids.Tentacle;
import com.Harbinger.Spore.Sentities.Organoids.Umarmer;
import com.Harbinger.Spore.Sentities.Organoids.Usurper;
import com.Harbinger.Spore.Sentities.Organoids.Verwa;
import com.Harbinger.Spore.Sentities.Organoids.Vigil;
import com.Harbinger.Spore.Sentities.Organoids.Womb;
import com.Harbinger.Spore.Sentities.Projectile.AcidBall;
import com.Harbinger.Spore.Sentities.Projectile.AdaptableProjectile;
import com.Harbinger.Spore.Sentities.Projectile.BileProjectile;
import com.Harbinger.Spore.Sentities.Projectile.DrownedFleshBomb;
import com.Harbinger.Spore.Sentities.Projectile.FallenAcidSack;
import com.Harbinger.Spore.Sentities.Projectile.FleshBomb;
import com.Harbinger.Spore.Sentities.Projectile.HarpoonProjectile;
import com.Harbinger.Spore.Sentities.Projectile.StingerProjectile;
import com.Harbinger.Spore.Sentities.Projectile.SyringeProjectile;
import com.Harbinger.Spore.Sentities.Projectile.ThrownBlockProjectile;
import com.Harbinger.Spore.Sentities.Projectile.ThrownBoomerang;
import com.Harbinger.Spore.Sentities.Projectile.ThrownItemProjectile;
import com.Harbinger.Spore.Sentities.Projectile.ThrownKnife;
import com.Harbinger.Spore.Sentities.Projectile.ThrownSickle;
import com.Harbinger.Spore.Sentities.Projectile.ThrownSpear;
import com.Harbinger.Spore.Sentities.Projectile.ThrownTumor;
import com.Harbinger.Spore.Sentities.Projectile.Vomit;
import com.Harbinger.Spore.Sentities.Projectile.VomitHohlBall;
import com.Harbinger.Spore.Sentities.Projectile.VomitUsurperBall;
import com.Harbinger.Spore.Sentities.Projectile.GunProjectiles.AssassinBullet;
import com.Harbinger.Spore.Sentities.Projectile.GunProjectiles.BileBullet;
import com.Harbinger.Spore.Sentities.Projectile.GunProjectiles.GoreBullet;
import com.Harbinger.Spore.Sentities.Utility.ArenaEntity;
import com.Harbinger.Spore.Sentities.Utility.CorpseEntity;
import com.Harbinger.Spore.Sentities.Utility.GastGeber;
import com.Harbinger.Spore.Sentities.Utility.HyperClaw;
import com.Harbinger.Spore.Sentities.Utility.Illusion;
import com.Harbinger.Spore.Sentities.Utility.InfEvoClaw;
import com.Harbinger.Spore.Sentities.Utility.InfectionTendril;
import com.Harbinger.Spore.Sentities.Utility.InfestedConstruct;
import com.Harbinger.Spore.Sentities.Utility.NukeEntity;
import com.Harbinger.Spore.Sentities.Utility.Reaper;
import com.Harbinger.Spore.Sentities.Utility.ScentEntity;
import com.Harbinger.Spore.Sentities.Utility.Specter;
import com.Harbinger.Spore.Sentities.Utility.TumoroidNuke;
import com.Harbinger.Spore.Sentities.Utility.Vanguard;
import com.Harbinger.Spore.Sentities.Utility.WaveEntity;
import java.util.function.Supplier;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.entity.EntityType.Builder;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class Sentities {
   public static DeferredRegister SPORE_ENTITIES;
   public static final MobCategory INFECTED;
   public static final MobCategory ORGANOID;
   public static final RegistryObject INF_HUMAN;
   public static final RegistryObject INF_HUSK;
   public static final RegistryObject INF_PLAYER;
   public static final RegistryObject KNIGHT;
   public static final RegistryObject PROTECTOR;
   public static final RegistryObject INEBRIATER;
   public static final RegistryObject SAUGLING;
   public static final RegistryObject GRIEFER;
   public static final RegistryObject BRAIOMIL;
   public static final RegistryObject INF_VILLAGER;
   public static final RegistryObject INF_DISEASED_VILLAGER;
   public static final RegistryObject INF_WANDERER;
   public static final RegistryObject INF_WITCH;
   public static final RegistryObject LEAPER;
   public static final RegistryObject SLASHER;
   public static final RegistryObject SPITTER;
   public static final RegistryObject THORN;
   public static final RegistryObject MEPHETIC;
   public static final RegistryObject JAGD;
   public static final RegistryObject SCAVENGER;
   public static final RegistryObject BLOATER;
   public static final RegistryObject NUCLEA;
   public static final RegistryObject SCAMPER;
   public static final RegistryObject INF_PILLAGER;
   public static final RegistryObject PLAGUED;
   public static final RegistryObject LACERATOR;
   public static final RegistryObject BIOBLOOB;
   public static final RegistryObject INF_HAZMAT;
   public static final RegistryObject INF_VINDICATOR;
   public static final RegistryObject INF_CONSTRUCT;
   public static final Supplier BAIRN;
   public static final RegistryObject INF_EVOKER;
   public static final RegistryObject HOWLER;
   public static final Supplier GORGON;
   public static final RegistryObject STALKER;
   public static final RegistryObject WENDIGO;
   public static final RegistryObject INQUISITOR;
   public static final Supplier GROBER;
   public static final RegistryObject HEVOKER;
   public static final RegistryObject HEVOKER_ARM;
   public static final RegistryObject BROTKATZE;
   public static final RegistryObject OGRE;
   public static final RegistryObject BRUTE;
   public static final RegistryObject BUSSER;
   public static final RegistryObject VOLATILE;
   public static final RegistryObject INF_DROWNED;
   public static final RegistryObject CHEMIST;
   public static final RegistryObject CONDUCTOR;
   public static final Supplier GARGOYLE;
   public static final RegistryObject VANGUARD;
   public static final Supplier REAPER;
   public static final RegistryObject NAIAD;
   public static final RegistryObject VIGIL;
   public static final RegistryObject DELUSIONARE;
   public static final RegistryObject UMARMED;
   public static final RegistryObject BRAUREI;
   public static final RegistryObject TENTACLE;
   public static final RegistryObject ILLUSION;
   public static final RegistryObject ARENA_TENDRIL;
   public static final RegistryObject GASTGABER;
   public static final RegistryObject SPECTER;
   public static final RegistryObject HVINDICATOR;
   public static final RegistryObject NUKE;
   public static final RegistryObject VOMIT_BALL;
   public static final Supplier DROWNED_FLESH_BOMB;
   public static final RegistryObject USURPER_VOMIT_BALL;
   public static final RegistryObject ACID_BALL;
   public static final RegistryObject ACID;
   public static final Supplier ASSASSIN_BULLET;
   public static final Supplier GORE_BULLET;
   public static final Supplier BILE_BULLET;
   public static final RegistryObject THROWN_SPEAR;
   public static final RegistryObject THROWN_BOOMERANG;
   public static final RegistryObject THROWN_KNIFE;
   public static final RegistryObject THROWN_TUMOR;
   public static final RegistryObject FALLEN_ACID_BULB;
   public static final RegistryObject BILE;
   public static final RegistryObject SPIT;
   public static final RegistryObject STINGER;
   public static final RegistryObject HARPOON;
   public static final RegistryObject THROWN_TOOL;
   public static final RegistryObject THROWN_SYRINGE;
   public static final RegistryObject THROWN_SICKEL;
   public static final RegistryObject THROWN_BLOCK;
   public static final RegistryObject FLESH_BOMB;
   public static final RegistryObject SCENT;
   public static final RegistryObject CLAW;
   public static final RegistryObject CORPSE_PIECE;
   public static final RegistryObject MOUND;
   public static final RegistryObject RECONSTRUCTOR;
   public static final RegistryObject VERVA;
   public static final RegistryObject USURPER;
   public static final RegistryObject PROTO;
   public static final Supplier HIVETUMOR;
   public static final RegistryObject TENDRIL;
   public static final RegistryObject TUMOROID_NUKE;
   public static final RegistryObject WAVE;
   public static final RegistryObject SIEGER;
   public static final RegistryObject SIEGER_TAIL;
   public static final RegistryObject HOWIT_ARM;
   public static final RegistryObject GAZENBREACHER;
   public static final RegistryObject KRAKEN;
   public static final RegistryObject LICKER;
   public static final RegistryObject HINDENBURG;
   public static final RegistryObject HOWITZER;
   public static final Supplier STALH;
   public static final RegistryObject HOHLFRESSER;
   public static final RegistryObject HOHLFRESSER_SEG;
   public static final Supplier STAHL_ARM;
   public static final Supplier LEVIATHAN;
   public static final Supplier LEVIATHAN_SEG;

   public static void register(IEventBus eventBus) {
      SPORE_ENTITIES.register(eventBus);
   }

   private static RegistryObject register(String registryname, Builder entityTypeBuilder) {
      return SPORE_ENTITIES.register(registryname, () -> entityTypeBuilder.build(registryname));
   }

   static {
      SPORE_ENTITIES = DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, "spore");
      INFECTED = MobCategory.create("infected", "infected", (Integer)SConfig.SERVER.mob_cap.get(), false, false, 128);
      ORGANOID = MobCategory.create("organoid", "organoid", 20, false, false, 64);
      INF_HUMAN = SPORE_ENTITIES.register("inf_human", () -> Builder.of((p_33002_, level) -> new InfectedHuman(level), INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_human")).toString()));
      INF_HUSK = SPORE_ENTITIES.register("inf_husk", () -> Builder.of((p_33002_, level) -> new InfectedHusk(level), INFECTED).sized(0.6F, 2.1F).build((new ResourceLocation("spore", "inf_husk")).toString()));
      INF_PLAYER = SPORE_ENTITIES.register("inf_player", () -> Builder.of(InfectedPlayer::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_player")).toString()));
      KNIGHT = SPORE_ENTITIES.register("knight", () -> Builder.of(Knight::new, INFECTED).sized(0.6F, 2.0F).build((new ResourceLocation("spore", "knight")).toString()));
      PROTECTOR = SPORE_ENTITIES.register("protector", () -> Builder.of(Protector::new, INFECTED).sized(0.6F, 2.0F).build((new ResourceLocation("spore", "protector")).toString()));
      INEBRIATER = SPORE_ENTITIES.register("inebriater", () -> Builder.of(Inebriator::new, INFECTED).sized(0.6F, 1.8F).build((new ResourceLocation("spore", "inebriater")).toString()));
      SAUGLING = SPORE_ENTITIES.register("saugling", () -> Builder.of(Saugling::new, INFECTED).sized(0.9F, 0.9F).build((new ResourceLocation("spore", "saugling")).toString()));
      GRIEFER = SPORE_ENTITIES.register("griefer", () -> Builder.of(Griefer::new, INFECTED).sized(0.8F, 2.1F).build((new ResourceLocation("spore", "griefer")).toString()));
      BRAIOMIL = SPORE_ENTITIES.register("braiomil", () -> Builder.of(Braionmil::new, INFECTED).sized(0.6F, 2.0F).build((new ResourceLocation("spore", "braiomil")).toString()));
      INF_VILLAGER = SPORE_ENTITIES.register("inf_villager", () -> Builder.of(InfectedVillager::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_villager")).toString()));
      INF_DISEASED_VILLAGER = SPORE_ENTITIES.register("inf_diseased_villager", () -> Builder.of(InfectedDiseasedVillager::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_diseased_villager")).toString()));
      INF_WANDERER = SPORE_ENTITIES.register("inf_wanderer", () -> Builder.of(InfectedWanderingTrader::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_wanderer")).toString()));
      INF_WITCH = SPORE_ENTITIES.register("inf_witch", () -> Builder.of(InfectedWitch::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_witch")).toString()));
      LEAPER = SPORE_ENTITIES.register("leaper", () -> Builder.of(Leaper::new, INFECTED).sized(0.6F, 2.3F).build((new ResourceLocation("spore", "leaper")).toString()));
      SLASHER = SPORE_ENTITIES.register("slasher", () -> Builder.of(Slasher::new, INFECTED).sized(0.6F, 2.2F).build((new ResourceLocation("spore", "slasher")).toString()));
      SPITTER = SPORE_ENTITIES.register("spitter", () -> Builder.of(Spitter::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "spitter")).toString()));
      THORN = SPORE_ENTITIES.register("thorn", () -> Builder.of(Thorn::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "thorn")).toString()));
      MEPHETIC = SPORE_ENTITIES.register("mephitic", () -> Builder.of(Mephetic::new, INFECTED).sized(0.6F, 2.2F).build((new ResourceLocation("spore", "mephitic")).toString()));
      JAGD = SPORE_ENTITIES.register("jagd", () -> Builder.of(Jagdhund::new, INFECTED).sized(1.3F, 1.1F).build((new ResourceLocation("spore", "jagd")).toString()));
      SCAVENGER = SPORE_ENTITIES.register("scavenger", () -> Builder.of(Scavenger::new, INFECTED).sized(1.3F, 1.1F).build((new ResourceLocation("spore", "scavenger")).toString()));
      BLOATER = SPORE_ENTITIES.register("bloater", () -> Builder.of(Bloater::new, INFECTED).sized(0.8F, 1.9F).build((new ResourceLocation("spore", "bloater")).toString()));
      NUCLEA = SPORE_ENTITIES.register("nuclea", () -> Builder.of(Nuclealave::new, INFECTED).sized(1.1F, 2.2F).build((new ResourceLocation("spore", "nuclea")).toString()));
      SCAMPER = SPORE_ENTITIES.register("scamper", () -> Builder.of(Scamper::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "scamper")).toString()));
      INF_PILLAGER = SPORE_ENTITIES.register("inf_pillager", () -> Builder.of(InfectedPillager::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_pillager")).toString()));
      PLAGUED = SPORE_ENTITIES.register("plagued", () -> Builder.of(Plagued::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "plagued")).toString()));
      LACERATOR = SPORE_ENTITIES.register("lacerator", () -> Builder.of(Lacerator::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "lacerator")).toString()));
      BIOBLOOB = SPORE_ENTITIES.register("biobloob", () -> Builder.of(Biobloob::new, INFECTED).sized(2.6F, 1.9F).build((new ResourceLocation("spore", "biobloob")).toString()));
      INF_HAZMAT = SPORE_ENTITIES.register("inf_hazmat", () -> Builder.of(InfectedHazmat::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_hazmat")).toString()));
      INF_VINDICATOR = SPORE_ENTITIES.register("inf_vindicator", () -> Builder.of(InfectedVendicator::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_vindicator")).toString()));
      INF_CONSTRUCT = SPORE_ENTITIES.register("inf_contruct", () -> Builder.of(InfestedConstruct::new, INFECTED).sized(1.5F, 2.6F).build((new ResourceLocation("spore", "inf_contruct")).toString()));
      BAIRN = SPORE_ENTITIES.register("bairn", () -> Builder.of(Bairn::new, INFECTED).sized(0.8F, 0.8F).build((new ResourceLocation("spore", "bairn")).toString()));
      INF_EVOKER = SPORE_ENTITIES.register("inf_evoker", () -> Builder.of(InfectedEvoker::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "inf_evoker")).toString()));
      HOWLER = SPORE_ENTITIES.register("howler", () -> Builder.of(Howler::new, INFECTED).sized(0.6F, 2.1F).build((new ResourceLocation("spore", "howler")).toString()));
      GORGON = SPORE_ENTITIES.register("gorgon", () -> Builder.of(Gorgon::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "gorgon")).toString()));
      STALKER = SPORE_ENTITIES.register("stalker", () -> Builder.of(Stalker::new, INFECTED).sized(0.6F, 2.3F).build((new ResourceLocation("spore", "stalker")).toString()));
      WENDIGO = SPORE_ENTITIES.register("wendigo", () -> Builder.of(Wendigo::new, INFECTED).sized(1.0F, 3.3F).build((new ResourceLocation("spore", "wendigo")).toString()));
      INQUISITOR = SPORE_ENTITIES.register("inquisitor", () -> Builder.of(Inquisitor::new, INFECTED).sized(1.0F, 2.8F).build((new ResourceLocation("spore", "inquisitor")).toString()));
      GROBER = SPORE_ENTITIES.register("grober", () -> Builder.of(Grober::new, INFECTED).sized(1.0F, 2.5F).build((new ResourceLocation("spore", "grober")).toString()));
      HEVOKER = SPORE_ENTITIES.register("hevoker", () -> Builder.of(Hevoker::new, INFECTED).sized(1.0F, 3.0F).build((new ResourceLocation("spore", "hevoker")).toString()));
      HEVOKER_ARM = SPORE_ENTITIES.register("hevoker_arm", () -> Builder.of(HyperClaw::new, INFECTED).sized(1.2F, 1.8F).build((new ResourceLocation("spore", "hevoker_arm")).toString()));
      BROTKATZE = SPORE_ENTITIES.register("brot", () -> Builder.of(Brot::new, INFECTED).sized(1.8F, 1.8F).build((new ResourceLocation("spore", "brot")).toString()));
      OGRE = SPORE_ENTITIES.register("ogre", () -> Builder.of(Ogre::new, INFECTED).sized(2.5F, 3.0F).build((new ResourceLocation("spore", "ogre")).toString()));
      BRUTE = SPORE_ENTITIES.register("brute", () -> Builder.of(Brute::new, INFECTED).sized(1.8F, 1.6F).build((new ResourceLocation("spore", "brute")).toString()));
      BUSSER = SPORE_ENTITIES.register("busser", () -> Builder.of(Busser::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "busser")).toString()));
      VOLATILE = SPORE_ENTITIES.register("volatile", () -> Builder.of(Volatile::new, INFECTED).sized(0.6F, 2.3F).build((new ResourceLocation("spore", "volatile")).toString()));
      INF_DROWNED = SPORE_ENTITIES.register("inf_drowned", () -> Builder.of(InfectedDrowned::new, INFECTED).sized(0.6F, 2.0F).build((new ResourceLocation("spore", "inf_drowned")).toString()));
      CHEMIST = SPORE_ENTITIES.register("chemist", () -> Builder.of(Chemist::new, INFECTED).sized(0.6F, 1.8F).build((new ResourceLocation("spore", "chemist")).toString()));
      CONDUCTOR = SPORE_ENTITIES.register("conductor", () -> Builder.of(Conductor::new, INFECTED).sized(0.6F, 2.2F).build((new ResourceLocation("spore", "chemist")).toString()));
      GARGOYLE = SPORE_ENTITIES.register("gargoyle", () -> Builder.of(Gargoyl::new, INFECTED).sized(0.6F, 1.9F).build((new ResourceLocation("spore", "gargoyle")).toString()));
      VANGUARD = SPORE_ENTITIES.register("vanguard", () -> Builder.of(Vanguard::new, INFECTED).sized(0.8F, 2.5F).build((new ResourceLocation("spore", "vanguard")).toString()));
      REAPER = SPORE_ENTITIES.register("reaper", () -> Builder.of(Reaper::new, INFECTED).sized(0.8F, 2.4F).build((new ResourceLocation("spore", "reaper")).toString()));
      NAIAD = SPORE_ENTITIES.register("naiad", () -> Builder.of(Naiad::new, INFECTED).sized(1.25F, 0.75F).build((new ResourceLocation("spore", "naiad")).toString()));
      VIGIL = SPORE_ENTITIES.register("vigil", () -> Builder.of(Vigil::new, ORGANOID).sized(1.0F, 3.0F).build((new ResourceLocation("spore", "vigil")).toString()));
      DELUSIONARE = SPORE_ENTITIES.register("delusioner", () -> Builder.of(Delusionare::new, ORGANOID).sized(1.0F, 3.0F).build((new ResourceLocation("spore", "delusioner")).toString()));
      UMARMED = SPORE_ENTITIES.register("umarmed", () -> Builder.of(Umarmer::new, ORGANOID).sized(1.0F, 3.0F).build((new ResourceLocation("spore", "umarmed")).toString()));
      BRAUREI = SPORE_ENTITIES.register("braurei", () -> Builder.of(Brauerei::new, ORGANOID).sized(3.0F, 3.0F).build((new ResourceLocation("spore", "braurei")).toString()));
      TENTACLE = SPORE_ENTITIES.register("tentacle", () -> Builder.of(Tentacle::new, ORGANOID).sized(1.0F, 1.0F).build((new ResourceLocation("spore", "tentacle")).toString()));
      ILLUSION = SPORE_ENTITIES.register("illusion", () -> Builder.of(Illusion::new, MobCategory.MISC).sized(1.0F, 2.0F).build((new ResourceLocation("spore", "illusion")).toString()));
      ARENA_TENDRIL = SPORE_ENTITIES.register("arena_tendril", () -> Builder.of(ArenaEntity::new, ORGANOID).sized(1.0F, 3.0F).build((new ResourceLocation("spore", "arena_tendril")).toString()));
      GASTGABER = SPORE_ENTITIES.register("gastgaber", () -> Builder.of(GastGeber::new, ORGANOID).sized(1.1F, 2.0F).build((new ResourceLocation("spore", "gastgaber")).toString()));
      SPECTER = SPORE_ENTITIES.register("specter", () -> Builder.of(Specter::new, INFECTED).sized(1.1F, 2.5F).build((new ResourceLocation("spore", "specter")).toString()));
      HVINDICATOR = SPORE_ENTITIES.register("hvindicator", () -> Builder.of(Hvindicator::new, INFECTED).sized(1.1F, 3.5F).build((new ResourceLocation("spore", "hvindicator")).toString()));
      NUKE = SPORE_ENTITIES.register("nuke", () -> Builder.of(NukeEntity::new, MobCategory.MISC).sized(1.1F, 3.0F).build((new ResourceLocation("spore", "nuke")).toString()));
      VOMIT_BALL = register("vomit_ball", Builder.of(VomitHohlBall::new, MobCategory.MISC).setCustomClientFactory((spawnEntity, level) -> new VomitHohlBall(level)).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      DROWNED_FLESH_BOMB = register("drowned_flesh_bomb", Builder.of(DrownedFleshBomb::new, MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      USURPER_VOMIT_BALL = register("usurper_vomit_ball", Builder.of(VomitUsurperBall::new, MobCategory.MISC).setCustomClientFactory((spawnEntity, level) -> new VomitUsurperBall(level)).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      ACID_BALL = register("acid_ball", Builder.of(AcidBall::new, MobCategory.MISC).setCustomClientFactory((spawnEntity, level) -> new AcidBall(level)).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      ACID = register("acid", Builder.of(Vomit::new, MobCategory.MISC).setCustomClientFactory(Vomit::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      ASSASSIN_BULLET = register("assassin_bullet", Builder.of(AssassinBullet::new, MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      GORE_BULLET = register("gore_bullet", Builder.of(GoreBullet::new, MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      BILE_BULLET = register("bile_bullet", Builder.of(BileBullet::new, MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      THROWN_SPEAR = register("thrown_spear", Builder.of(ThrownSpear::new, MobCategory.MISC).setCustomClientFactory(ThrownSpear::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      THROWN_BOOMERANG = register("thrown_boomerang", Builder.of(ThrownBoomerang::new, MobCategory.MISC).setCustomClientFactory(ThrownBoomerang::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(1.0F, 0.5F));
      THROWN_KNIFE = register("thrown_knife", Builder.of(ThrownKnife::new, MobCategory.MISC).setCustomClientFactory(ThrownKnife::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      THROWN_TUMOR = register("thrown_tumor", Builder.of(ThrownTumor::new, MobCategory.MISC).setCustomClientFactory(ThrownTumor::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      FALLEN_ACID_BULB = register("fallen_acid_sack", Builder.of((p_33002_, level) -> new FallenAcidSack(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.4F, 0.4F));
      BILE = register("bile", Builder.of((p_33002_, level) -> new BileProjectile(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.4F, 0.4F));
      SPIT = register("spit", Builder.of((p_33002_, level) -> new AdaptableProjectile(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.4F, 0.4F));
      STINGER = register("stinger", Builder.of((p_33002_, level) -> new StingerProjectile(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.4F, 0.4F));
      HARPOON = register("harpoon", Builder.of((p_33002_, level) -> new HarpoonProjectile(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.4F, 0.4F));
      THROWN_TOOL = register("thrown_tool", Builder.of((p_33002_, level) -> new ThrownItemProjectile(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.4F, 0.4F));
      THROWN_SYRINGE = register("thrown_syringe", Builder.of((p_33002_, level) -> new SyringeProjectile(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.4F, 0.4F));
      THROWN_SICKEL = register("thrown_sickle", Builder.of((p_33002_, level) -> new ThrownSickle(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.4F, 0.4F));
      THROWN_BLOCK = register("thrown_block", Builder.of((p_33002_, level) -> new ThrownBlockProjectile(level), MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(1.0F, 1.0F));
      FLESH_BOMB = register("flesh_bomb", Builder.of(FleshBomb::new, MobCategory.MISC).setCustomClientFactory(FleshBomb::new).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5F, 0.5F));
      SCENT = SPORE_ENTITIES.register("scent", () -> Builder.of(ScentEntity::new, MobCategory.MISC).sized(0.2F, 0.2F).build((new ResourceLocation("spore", "scent")).toString()));
      CLAW = SPORE_ENTITIES.register("claw", () -> Builder.of(InfEvoClaw::new, INFECTED).sized(0.5F, 1.0F).build((new ResourceLocation("spore", "claw")).toString()));
      CORPSE_PIECE = SPORE_ENTITIES.register("corpse_piece", () -> Builder.of(CorpseEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).clientTrackingRange(10).build((new ResourceLocation("spore", "corpse_piece")).toString()));
      MOUND = SPORE_ENTITIES.register("mound", () -> Builder.of(Mound::new, ORGANOID).sized(0.3F, 0.3F).build((new ResourceLocation("spore", "mound")).toString()));
      RECONSTRUCTOR = SPORE_ENTITIES.register("reconstructor", () -> Builder.of(Womb::new, ORGANOID).sized(1.0F, 1.0F).build((new ResourceLocation("spore", "reconstructor")).toString()));
      VERVA = SPORE_ENTITIES.register("verva", () -> Builder.of(Verwa::new, ORGANOID).sized(1.0F, 2.0F).build((new ResourceLocation("spore", "verva")).toString()));
      USURPER = SPORE_ENTITIES.register("usurper", () -> Builder.of(Usurper::new, ORGANOID).sized(1.0F, 2.2F).build((new ResourceLocation("spore", "usurper")).toString()));
      PROTO = SPORE_ENTITIES.register("proto", () -> Builder.of(Proto::new, ORGANOID).sized(1.0F, 3.5F).build((new ResourceLocation("spore", "proto")).toString()));
      HIVETUMOR = SPORE_ENTITIES.register("hivetumor", () -> Builder.of(HiveTumor::new, ORGANOID).sized(1.2F, 3.0F).build((new ResourceLocation("spore", "hivetumor")).toString()));
      TENDRIL = SPORE_ENTITIES.register("tendril", () -> Builder.of(InfectionTendril::new, MobCategory.MISC).sized(0.8F, 0.1F).build((new ResourceLocation("spore", "tendril")).toString()));
      TUMOROID_NUKE = SPORE_ENTITIES.register("tumoroid_nuke", () -> Builder.of(TumoroidNuke::new, MobCategory.MISC).sized(3.0F, 3.0F).build((new ResourceLocation("spore", "tumoroid_nuke")).toString()));
      WAVE = SPORE_ENTITIES.register("wave", () -> Builder.of(WaveEntity::new, MobCategory.MISC).sized(0.8F, 0.1F).build((new ResourceLocation("spore", "wave")).toString()));
      SIEGER = SPORE_ENTITIES.register("sieger", () -> Builder.of(Sieger::new, INFECTED).sized(2.5F, 3.0F).build((new ResourceLocation("spore", "sieger")).toString()));
      SIEGER_TAIL = SPORE_ENTITIES.register("sieger_tail", () -> Builder.of(SiegerTail::new, MobCategory.MISC).sized(2.1F, 1.0F).build((new ResourceLocation("spore", "sieger_tail")).toString()));
      HOWIT_ARM = SPORE_ENTITIES.register("howit_arm", () -> Builder.of(HowitzerArm::new, MobCategory.MISC).sized(2.1F, 1.0F).build((new ResourceLocation("spore", "howit_arm")).toString()));
      GAZENBREACHER = SPORE_ENTITIES.register("gazenbreacher", () -> Builder.of(Gazenbrecher::new, INFECTED).sized(3.5F, 3.0F).build((new ResourceLocation("spore", "gazenbreacher")).toString()));
      KRAKEN = SPORE_ENTITIES.register("kraken", () -> Builder.of(Grakensenker::new, INFECTED).sized(3.0F, 3.0F).build((new ResourceLocation("spore", "kraken")).toString()));
      LICKER = SPORE_ENTITIES.register("licker", () -> Builder.of(Licker::new, MobCategory.MISC).sized(1.4F, 1.0F).build((new ResourceLocation("spore", "licker")).toString()));
      HINDENBURG = SPORE_ENTITIES.register("hindenburg", () -> Builder.of(Hinderburg::new, INFECTED).sized(5.0F, 5.0F).build((new ResourceLocation("spore", "hindenburg")).toString()));
      HOWITZER = SPORE_ENTITIES.register("howitzer", () -> Builder.of(Howitzer::new, INFECTED).sized(5.0F, 5.0F).build((new ResourceLocation("spore", "howitzer")).toString()));
      STALH = SPORE_ENTITIES.register("stahl", () -> Builder.of(Stahlmorder::new, INFECTED).sized(3.0F, 6.0F).build((new ResourceLocation("spore", "stahl")).toString()));
      HOHLFRESSER = SPORE_ENTITIES.register("hohlfresser", () -> Builder.of(Hohlfresser::new, INFECTED).sized(3.5F, 3.5F).build((new ResourceLocation("spore", "hohlfresser")).toString()));
      HOHLFRESSER_SEG = SPORE_ENTITIES.register("hohlfresser_seg", () -> Builder.of(HohlMultipart::new, INFECTED).sized(3.5F, 3.5F).build((new ResourceLocation("spore", "hohlfresser_seg")).toString()));
      STAHL_ARM = SPORE_ENTITIES.register("stahl_arm", () -> Builder.of(StalhArm::new, MobCategory.MISC).sized(3.0F, 1.0F).build((new ResourceLocation("spore", "stahl_arm")).toString()));
      LEVIATHAN = SPORE_ENTITIES.register("leviathan", () -> Builder.of(Leviathan::new, INFECTED).sized(3.5F, 3.5F).build((new ResourceLocation("spore", "leviathan")).toString()));
      LEVIATHAN_SEG = SPORE_ENTITIES.register("leviathan_seg", () -> Builder.of(LeviathanMultipart::new, INFECTED).sized(3.5F, 3.5F).build((new ResourceLocation("spore", "leviathan_seg")).toString()));
   }
}
