package com.Harbinger.Spore.Core;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class Ssounds {
   public static final DeferredRegister SOUNDS;
   public static final RegistryObject CORRUPTED_RECORD;
   public static final RegistryObject FORGOTTEN_PATIENT;
   public static final RegistryObject FORSAKEN_FUTURE;
   public static final RegistryObject NUKE;
   public static final RegistryObject AREA_AMBIENT;
   public static final RegistryObject REBIRTH;
   public static final RegistryObject INF_DAMAGE;
   public static final RegistryObject INF_GROWL;
   public static final RegistryObject HOWLER_GROWL;
   public static final RegistryObject INF_VILLAGER_DAMAGE;
   public static final RegistryObject INF_VILLAGER_GROWL;
   public static final RegistryObject INF_VILLAGER_DEATH;
   public static final RegistryObject INF_EVOKER_DAMAGE;
   public static final RegistryObject INF_EVOKER_GROWL;
   public static final RegistryObject INF_EVOKER_DEATH;
   public static final RegistryObject BRAIOMIL_ATTACK;
   public static final RegistryObject SIEGER_AMBIENT;
   public static final RegistryObject SIEGER_BITE;
   public static final RegistryObject GAZEN_AMBIENT;
   public static final RegistryObject HINDEN_AMBIENT;
   public static final RegistryObject BRAUREI_AMBIENT;
   public static final RegistryObject HINDEN_NUKE;
   public static final RegistryObject SONAR;
   public static final RegistryObject LANDING;
   public static final RegistryObject HOWITZER_AMBIENT;
   public static final RegistryObject FALLING_BOMB;
   public static final RegistryObject SIGNAL;
   public static final RegistryObject UMARMER_AMBIENT;
   public static final RegistryObject VIGIL_AMBIENT;
   public static final RegistryObject WENDIGO_AMBIENT;
   public static final RegistryObject WENDIGO_SCREECH;
   public static final RegistryObject WOMB_AMBIENT;
   public static final RegistryObject USURPER_AMBIENT;
   public static final RegistryObject INQUISITOR_AMBIENT;
   public static final RegistryObject BROT_AMBIENT;
   public static final RegistryObject DELUSIONER_AMBIENT;
   public static final RegistryObject DELUSIONER_CASTING;
   public static final RegistryObject BIOBLOB;
   public static final RegistryObject SPIT;
   public static final RegistryObject MADNESS;
   public static final RegistryObject LIMB_SLASH;
   public static final RegistryObject PROTO_AMBIENT;
   public static final RegistryObject FUNGAL_BURST;
   public static final RegistryObject HEART_BEAT;
   public static final RegistryObject PUFF;
   public static final RegistryObject PRINTING;
   public static final RegistryObject GAST_AMBIENT;
   public static final RegistryObject SAW_SOUND;
   public static final RegistryObject ENGINE;
   public static final RegistryObject SPECTER_AMBIENT;
   public static final RegistryObject CONSTRUCT_AMBIENT;
   public static final RegistryObject SCAVENGER_SCREECH;
   public static final RegistryObject BROKEN_SCREAMS;
   public static final RegistryObject HYPER_EVOLVE;
   public static final RegistryObject OGRE_AMBIENT;
   public static final RegistryObject CALAMITY_SPAWN;
   public static final RegistryObject CALAMITY_INCOMING;
   public static final RegistryObject SURGERY;
   public static final RegistryObject EVOLVE_HURT;
   public static final RegistryObject HEVOKER_AMBIENT;
   public static final RegistryObject HINDICATOR_AMBIENT;
   public static final RegistryObject INFECTED_WEAPON_THROW;
   public static final RegistryObject INFECTED_WEAPON_HIT_ENTITY;
   public static final RegistryObject INFECTED_WEAPON_HIT_BLOCK;
   public static final RegistryObject CDU_INSERT;
   public static final RegistryObject CDU_AMBIENT;
   public static final RegistryObject CLEAVER_SPIN;
   public static final RegistryObject INFECTED_PICKAXE;
   public static final RegistryObject REAVER_REAVE;
   public static final RegistryObject SABER_LEAP;
   public static final RegistryObject SCANNER_ITEM;
   public static final RegistryObject SCANNER_EMPTY;
   public static final RegistryObject SCANNER_MOB;
   public static final RegistryObject VIGIL_EYE_USE;
   public static final RegistryObject SYRINGE_SUCK;
   public static final RegistryObject SYRINGE_INJECT;
   public static final RegistryObject PCI_INJECT;
   public static final RegistryObject REAGENT;
   public static final RegistryObject INFECTED_GEAR_BREAK;
   public static final RegistryObject INFECTED_GEAR_EQUIP;
   public static final RegistryObject SHIELD_BASH;
   public static final RegistryObject TUMOROID_EXPLOSION;
   public static final RegistryObject INF_VILLAGER_AMBIENT;
   public static final RegistryObject INF_PILLAGER_AMBIENT;
   public static final RegistryObject ADVENTURER_AMBIENT;
   public static final RegistryObject TRADER_AMBIENT;
   public static final RegistryObject WITCH_AMBIENT;
   public static final RegistryObject DROWNED_AMBIENT;
   public static final RegistryObject HUSK_AMBIENT;
   public static final RegistryObject VINDICATOR_AMBIENT;
   public static final RegistryObject SCAMPER_AMBIENT;
   public static final RegistryObject ORGANOID_DAMAGE;
   public static final RegistryObject HYPER_DAMAGE;
   public static final RegistryObject CALAMITY_DAMAGE;
   public static final RegistryObject INEBRIATER_INJECT;
   public static final RegistryObject LACERATOR_AMBIENT;
   public static final RegistryObject SAUGLING_AMBIENT;
   public static final RegistryObject PLAGUED_AMBIENT;
   public static final RegistryObject SAUGLING_CHEST_AMBIENT;
   public static final RegistryObject SAUGLING_JUMPSCARE;
   public static final RegistryObject SCIENTIST_AMBIENT;
   public static final RegistryObject SPORE_BURST;
   public static final RegistryObject WORM_DIGGING;
   public static final RegistryObject HOHL_AMBIENT;
   public static final RegistryObject CALAMITY_DEATH;
   public static final RegistryObject SYRINGE_RELOAD;
   public static final RegistryObject SYRINGE_SPIN;
   public static final RegistryObject SYRINGE_SHOOT;
   public static final RegistryObject SYRINGE_GUN_INJECT;
   public static final RegistryObject SCIENTIST_FUSE;
   public static final RegistryObject CHEMIST_FUSE;
   public static final RegistryObject EVOKER_SUCK;
   public static final RegistryObject HEXEN_SUCK;
   public static final RegistryObject HEXEN_BLOW;
   public static final RegistryObject SLASHER_PULL;
   public static final RegistryObject SLASHER_STAB;
   public static final RegistryObject SPECTER_CLOAK;
   public static final RegistryObject SPECTER_UNCLOAK;
   public static final RegistryObject VANGUARD_AMBIENT;
   public static final RegistryObject VANGUARD_SLASH;
   public static final RegistryObject VANGUARD_SHOOT;
   public static final RegistryObject VANGUARD_FIREWORKS;
   public static final RegistryObject VANGUARD_GRIEF;
   public static final RegistryObject VANGUARD_CALL;
   public static final RegistryObject VANGUARD_RAID;
   public static final RegistryObject KRAKEN_GROWL;
   public static final RegistryObject BAIRN;
   public static final RegistryObject STAHL_AMBIENT;
   public static final RegistryObject STAHL_KICK;
   public static final RegistryObject STAHL_SLAP;
   public static final RegistryObject STAHL_SLASH;
   public static final RegistryObject PHAYRES_SCREECH;
   public static final RegistryObject TUMOR_SPAWN;
   public static final RegistryObject OMNI_AMBIENT;
   public static final RegistryObject GROBER_AMBIENT;
   public static final RegistryObject TUMOR_AMBIENT;
   public static final RegistryObject FUNGAL_BOOM;
   public static final RegistryObject ELECTRIC;
   public static final RegistryObject GROBER_SLAP;
   public static final RegistryObject GROBER_SMASH;
   public static final RegistryObject GROBER_KICK;
   public static final RegistryObject GROBER_CHARGE;
   public static final RegistryObject GROBER_CHOKE;
   public static final RegistryObject ELECTRIC_SPARK;
   public static final RegistryObject ELECTRIC_DISCHARGE;
   public static final RegistryObject LEVIATHAN_AMBIENT;
   public static final RegistryObject REAPER_AMBIENT;
   public static final RegistryObject REAPER_ATTACK;
   public static final RegistryObject REAPER_SPIT;
   public static final RegistryObject REAPER_HARVEST;
   public static final RegistryObject REAPER_COMPOST;
   public static final RegistryObject BIOGUN_NO_AMMO;
   public static final RegistryObject MISTMAKER_BITE;
   public static final RegistryObject MISTMAKER_BULLET_BLOCK;
   public static final RegistryObject MISTMAKER_BULLET_ENTITY;
   public static final RegistryObject MISTMAKER_DEPLOY;
   public static final RegistryObject MISTMAKER_RETRACT;
   public static final RegistryObject MISTMAKER_SHOT;
   public static final RegistryObject BILE_BLASTER_SHOT;
   public static final RegistryObject BILE_BLASTER_BULLET_BLOCK;
   public static final RegistryObject BILE_BLASTER_BULLET_ENTITY;
   public static final RegistryObject ASSASSIN_SHOT;
   public static final RegistryObject ASSASSIN_BULLET_BLOCK;
   public static final RegistryObject ASSASSIN_BULLET_ENTITY;
   public static final RegistryObject BIOGUN_RELOAD;
   public static final RegistryObject BIOGUN_HIT_PLAYER;
   public static final RegistryObject GORGON_SPEW;
   public static final RegistryObject BANE_OF_SETTLEMENT;
   public static final RegistryObject BICENTENNIAL;
   public static final RegistryObject BROKEN_REFLECTION;
   public static final RegistryObject CYCLE_OF_EVOLUTION;
   public static final RegistryObject DECAY;
   public static final RegistryObject DESOLATION;
   public static final RegistryObject ENDLESS_FEAST;
   public static final RegistryObject FALL_OF_MAN;
   public static final RegistryObject INSOLENCE;
   public static final RegistryObject INSOLENCE_INTRO;
   public static final RegistryObject MANMADE_HORRORS;
   public static final RegistryObject MENTAL_MUTILATION;
   public static final RegistryObject MYCONAUT;
   public static final RegistryObject MYCONOCLAST;
   public static final RegistryObject MYCOPHOBIA;
   public static final RegistryObject NATURAL_OCCURANCE;
   public static final RegistryObject NEUROGENESIS;
   public static final RegistryObject NOURISHMENT;
   public static final RegistryObject ONCE_HERE;
   public static final RegistryObject PROJECT_REGENESIS;
   public static final RegistryObject PROTOTYPE;
   public static final RegistryObject RECLAIMATION;
   public static final RegistryObject REPURPOSED;
   public static final RegistryObject RESTLESS_REACH;
   public static final RegistryObject ROADS_ONCE_TRAVELLED;
   public static final RegistryObject ROT;
   public static final RegistryObject SLEEPLESS_DREAMING;
   public static final RegistryObject SOMETHING_ONCE_GREAT;
   public static final RegistryObject SPORE_BURST_SONG;
   public static final RegistryObject START_ANEW;
   public static final RegistryObject SYNAPTIC_RELAPSE;
   public static final RegistryObject THE_SOIL_TALKS;
   public static final RegistryObject THEY_AWAKEN;
   public static final RegistryObject THEY_GROW_BELOW;
   public static final RegistryObject THEY_LISTEN;
   public static final RegistryObject VIRULENT_VIGIL;
   public static final RegistryObject WHISPERS;
   public static final RegistryObject WHAT_WE_BECOME;

   public static void register(IEventBus eventBus) {
      SOUNDS.register(eventBus);
   }

   private static RegistryObject soundRegistry(String id) {
      return SOUNDS.register(id, () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("spore", id)));
   }

   private Ssounds() {
   }

   static {
      SOUNDS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, "spore");
      CORRUPTED_RECORD = soundRegistry("corrupted_record");
      FORGOTTEN_PATIENT = soundRegistry("forgotten_patient");
      FORSAKEN_FUTURE = soundRegistry("forsaken_future");
      NUKE = soundRegistry("nuke");
      AREA_AMBIENT = soundRegistry("spore_area_ambient");
      REBIRTH = soundRegistry("rebirth");
      INF_DAMAGE = soundRegistry("inf_damage");
      INF_GROWL = soundRegistry("inf_growl");
      HOWLER_GROWL = soundRegistry("howler_growl");
      INF_VILLAGER_DAMAGE = soundRegistry("inf_villager_damage");
      INF_VILLAGER_GROWL = soundRegistry("inf_villager_growl");
      INF_VILLAGER_DEATH = soundRegistry("inf_villager_death");
      INF_EVOKER_DAMAGE = soundRegistry("inf_evoker_damage");
      INF_EVOKER_GROWL = soundRegistry("inf_evoker_growl");
      INF_EVOKER_DEATH = soundRegistry("inf_evoker_death");
      BRAIOMIL_ATTACK = soundRegistry("braiomil_attack");
      SIEGER_AMBIENT = soundRegistry("sieger_ambient");
      SIEGER_BITE = soundRegistry("sieger_bite");
      GAZEN_AMBIENT = soundRegistry("gazen_ambient");
      HINDEN_AMBIENT = soundRegistry("hinden_ambient");
      BRAUREI_AMBIENT = soundRegistry("braurei_ambient");
      HINDEN_NUKE = soundRegistry("hinden_nuke");
      SONAR = soundRegistry("sonar");
      LANDING = soundRegistry("landing");
      HOWITZER_AMBIENT = soundRegistry("howitzer_ambient");
      FALLING_BOMB = soundRegistry("falling_bomb");
      SIGNAL = soundRegistry("signal");
      UMARMER_AMBIENT = soundRegistry("umarmer_ambient");
      VIGIL_AMBIENT = soundRegistry("vigil_ambient");
      WENDIGO_AMBIENT = soundRegistry("wendigo_ambient");
      WENDIGO_SCREECH = soundRegistry("wendigo_screech");
      WOMB_AMBIENT = soundRegistry("womb_ambient");
      USURPER_AMBIENT = soundRegistry("usurper_ambient");
      INQUISITOR_AMBIENT = soundRegistry("inquisitor_ambient");
      BROT_AMBIENT = soundRegistry("brot_ambient");
      DELUSIONER_AMBIENT = soundRegistry("delusioner_ambient");
      DELUSIONER_CASTING = soundRegistry("delusioner_casting");
      BIOBLOB = soundRegistry("bioblob");
      SPIT = soundRegistry("spit");
      MADNESS = soundRegistry("madness");
      LIMB_SLASH = soundRegistry("limb_slash");
      PROTO_AMBIENT = soundRegistry("proto_ambient");
      FUNGAL_BURST = soundRegistry("fungal_burst");
      HEART_BEAT = soundRegistry("heart_beat");
      PUFF = soundRegistry("puff");
      PRINTING = soundRegistry("printing");
      GAST_AMBIENT = soundRegistry("gast_ambient");
      SAW_SOUND = soundRegistry("saw_sound");
      ENGINE = soundRegistry("engine");
      SPECTER_AMBIENT = soundRegistry("specter_ambient");
      CONSTRUCT_AMBIENT = soundRegistry("construct_ambient");
      SCAVENGER_SCREECH = soundRegistry("scavenger_screech");
      BROKEN_SCREAMS = soundRegistry("broken_screams");
      HYPER_EVOLVE = soundRegistry("hyper_evolve");
      OGRE_AMBIENT = soundRegistry("ogre_ambient");
      CALAMITY_SPAWN = soundRegistry("calamity_spawn");
      CALAMITY_INCOMING = soundRegistry("calamity_incoming");
      SURGERY = soundRegistry("surgery");
      EVOLVE_HURT = soundRegistry("evolve_hurt");
      HEVOKER_AMBIENT = soundRegistry("hevoker_ambient");
      HINDICATOR_AMBIENT = soundRegistry("hindicator_ambient");
      INFECTED_WEAPON_THROW = soundRegistry("infected_weapon_throw");
      INFECTED_WEAPON_HIT_ENTITY = soundRegistry("infected_weapon_hit_entity");
      INFECTED_WEAPON_HIT_BLOCK = soundRegistry("infected_weapon_hit_block");
      CDU_INSERT = soundRegistry("cdu_insert");
      CDU_AMBIENT = soundRegistry("cdu_ambient");
      CLEAVER_SPIN = soundRegistry("cleaver_spin");
      INFECTED_PICKAXE = soundRegistry("infected_pickaxe");
      REAVER_REAVE = soundRegistry("reaver_reave");
      SABER_LEAP = soundRegistry("saber_leap");
      SCANNER_ITEM = soundRegistry("scanner_item");
      SCANNER_EMPTY = soundRegistry("scanner_empty");
      SCANNER_MOB = soundRegistry("scanner_mob");
      VIGIL_EYE_USE = soundRegistry("vigil_eye_use");
      SYRINGE_SUCK = soundRegistry("syringe_suck");
      SYRINGE_INJECT = soundRegistry("syringe_inject");
      PCI_INJECT = soundRegistry("pci_inject");
      REAGENT = soundRegistry("reagent");
      INFECTED_GEAR_BREAK = soundRegistry("infected_gear_break");
      INFECTED_GEAR_EQUIP = soundRegistry("infected_gear_equip");
      SHIELD_BASH = soundRegistry("shield_bash");
      TUMOROID_EXPLOSION = soundRegistry("tumoroid_explosion");
      INF_VILLAGER_AMBIENT = soundRegistry("villager_ambient");
      INF_PILLAGER_AMBIENT = soundRegistry("pillager_ambient");
      ADVENTURER_AMBIENT = soundRegistry("adventurer_ambient");
      TRADER_AMBIENT = soundRegistry("trader_ambient");
      WITCH_AMBIENT = soundRegistry("witch_ambient");
      DROWNED_AMBIENT = soundRegistry("drowned_ambient");
      HUSK_AMBIENT = soundRegistry("husk_ambient");
      VINDICATOR_AMBIENT = soundRegistry("vindicator_ambient");
      SCAMPER_AMBIENT = soundRegistry("scamper_ambient");
      ORGANOID_DAMAGE = soundRegistry("organoid_damage");
      HYPER_DAMAGE = soundRegistry("hyper_damage");
      CALAMITY_DAMAGE = soundRegistry("calamity_damage");
      INEBRIATER_INJECT = soundRegistry("inebriater_inject");
      LACERATOR_AMBIENT = soundRegistry("lacerator_ambient");
      SAUGLING_AMBIENT = soundRegistry("saugling_ambient");
      PLAGUED_AMBIENT = soundRegistry("plagued_ambient");
      SAUGLING_CHEST_AMBIENT = soundRegistry("saugling_chest_ambient");
      SAUGLING_JUMPSCARE = soundRegistry("saugling_jumpscare");
      SCIENTIST_AMBIENT = soundRegistry("scientist_ambient");
      SPORE_BURST = soundRegistry("spore_burst");
      WORM_DIGGING = soundRegistry("worm_digging");
      HOHL_AMBIENT = soundRegistry("hohl_ambient");
      CALAMITY_DEATH = soundRegistry("calamity_death");
      SYRINGE_RELOAD = soundRegistry("syringe_reload");
      SYRINGE_SPIN = soundRegistry("syringe_spin");
      SYRINGE_SHOOT = soundRegistry("syringe_shoot");
      SYRINGE_GUN_INJECT = soundRegistry("syringe_gun_inject");
      SCIENTIST_FUSE = soundRegistry("scientist_fuse");
      CHEMIST_FUSE = soundRegistry("chemist_fuse");
      EVOKER_SUCK = soundRegistry("evoker_suck");
      HEXEN_SUCK = soundRegistry("hexen_suck");
      HEXEN_BLOW = soundRegistry("hexen_blow");
      SLASHER_PULL = soundRegistry("slasher_pull");
      SLASHER_STAB = soundRegistry("slasher_stab");
      SPECTER_CLOAK = soundRegistry("specter_cloak");
      SPECTER_UNCLOAK = soundRegistry("specter_uncloak");
      VANGUARD_AMBIENT = soundRegistry("vanguard_ambient");
      VANGUARD_SLASH = soundRegistry("vanguard_slash");
      VANGUARD_SHOOT = soundRegistry("vanguard_shoot");
      VANGUARD_FIREWORKS = soundRegistry("vanguard_fireworks");
      VANGUARD_GRIEF = soundRegistry("vanguard_grief");
      VANGUARD_CALL = soundRegistry("vanguard_call");
      VANGUARD_RAID = soundRegistry("vanguard_raid");
      KRAKEN_GROWL = soundRegistry("kraken_growl");
      BAIRN = soundRegistry("bairn");
      STAHL_AMBIENT = soundRegistry("stahl_ambient");
      STAHL_KICK = soundRegistry("stahl_kick");
      STAHL_SLAP = soundRegistry("stahl_slap");
      STAHL_SLASH = soundRegistry("stahl_slash");
      PHAYRES_SCREECH = soundRegistry("phayres_screech");
      TUMOR_SPAWN = soundRegistry("tumor_spawn");
      OMNI_AMBIENT = soundRegistry("omni_ambient");
      GROBER_AMBIENT = soundRegistry("grober_ambient");
      TUMOR_AMBIENT = soundRegistry("tumor_ambient");
      FUNGAL_BOOM = soundRegistry("fungal_boom");
      ELECTRIC = soundRegistry("electric");
      GROBER_SLAP = soundRegistry("grober_slap");
      GROBER_SMASH = soundRegistry("grober_smash");
      GROBER_KICK = soundRegistry("grober_kick");
      GROBER_CHARGE = soundRegistry("grober_charge");
      GROBER_CHOKE = soundRegistry("grober_choke");
      ELECTRIC_SPARK = soundRegistry("electric_spark");
      ELECTRIC_DISCHARGE = soundRegistry("electric_discharge");
      LEVIATHAN_AMBIENT = soundRegistry("leviathan_ambient");
      REAPER_AMBIENT = soundRegistry("reaper_ambient");
      REAPER_ATTACK = soundRegistry("reaper_attack");
      REAPER_SPIT = soundRegistry("reaper_spit");
      REAPER_HARVEST = soundRegistry("reaper_harvest");
      REAPER_COMPOST = soundRegistry("reaper_compost");
      BIOGUN_NO_AMMO = soundRegistry("biogun_out_of_ammo");
      MISTMAKER_BITE = soundRegistry("mistmaker_bite");
      MISTMAKER_BULLET_BLOCK = soundRegistry("mistmaker_bullet_block");
      MISTMAKER_BULLET_ENTITY = soundRegistry("mistmaker_bullet_entity");
      MISTMAKER_DEPLOY = soundRegistry("mistmaker_deploy");
      MISTMAKER_RETRACT = soundRegistry("mistmaker_retract");
      MISTMAKER_SHOT = soundRegistry("mistmaker_shot");
      BILE_BLASTER_SHOT = soundRegistry("bile_blaster_shot");
      BILE_BLASTER_BULLET_BLOCK = soundRegistry("bile_blaster_bullet_block");
      BILE_BLASTER_BULLET_ENTITY = soundRegistry("bile_blaster_bullet_entity");
      ASSASSIN_SHOT = soundRegistry("assassin_shot");
      ASSASSIN_BULLET_BLOCK = soundRegistry("assassin_bullet_block");
      ASSASSIN_BULLET_ENTITY = soundRegistry("assassin_bullet_entity");
      BIOGUN_RELOAD = soundRegistry("biogun_reload");
      BIOGUN_HIT_PLAYER = soundRegistry("biogun_hit_player");
      GORGON_SPEW = soundRegistry("gorgon_spew");
      BANE_OF_SETTLEMENT = soundRegistry("bane_of_settlement");
      BICENTENNIAL = soundRegistry("bicentennial");
      BROKEN_REFLECTION = soundRegistry("broken_reflection");
      CYCLE_OF_EVOLUTION = soundRegistry("cycle_of_evolution");
      DECAY = soundRegistry("decay");
      DESOLATION = soundRegistry("desolation");
      ENDLESS_FEAST = soundRegistry("endless_feast");
      FALL_OF_MAN = soundRegistry("fall_of_man");
      INSOLENCE = soundRegistry("insolence");
      INSOLENCE_INTRO = soundRegistry("insolence_intro");
      MANMADE_HORRORS = soundRegistry("manmade_horrors");
      MENTAL_MUTILATION = soundRegistry("mental_mutilation");
      MYCONAUT = soundRegistry("myconaut");
      MYCONOCLAST = soundRegistry("myconoclast");
      MYCOPHOBIA = soundRegistry("mycophobia");
      NATURAL_OCCURANCE = soundRegistry("natural_occurance");
      NEUROGENESIS = soundRegistry("neurogenesis");
      NOURISHMENT = soundRegistry("nourishment");
      ONCE_HERE = soundRegistry("once_here");
      PROJECT_REGENESIS = soundRegistry("project_regenesis");
      PROTOTYPE = soundRegistry("prototype");
      RECLAIMATION = soundRegistry("reclaimation");
      REPURPOSED = soundRegistry("repurposed");
      RESTLESS_REACH = soundRegistry("restless_reach");
      ROADS_ONCE_TRAVELLED = soundRegistry("roads_once_travelled");
      ROT = soundRegistry("rot");
      SLEEPLESS_DREAMING = soundRegistry("sleepless_dreaming");
      SOMETHING_ONCE_GREAT = soundRegistry("something_once_great");
      SPORE_BURST_SONG = soundRegistry("spore_burst_song");
      START_ANEW = soundRegistry("start_anew");
      SYNAPTIC_RELAPSE = soundRegistry("synaptic_relapse");
      THE_SOIL_TALKS = soundRegistry("the_soil_talks");
      THEY_AWAKEN = soundRegistry("they_awaken");
      THEY_GROW_BELOW = soundRegistry("they_grow_below");
      THEY_LISTEN = soundRegistry("they_listen");
      VIRULENT_VIGIL = soundRegistry("virulent_vigil");
      WHISPERS = soundRegistry("whispers");
      WHAT_WE_BECOME = soundRegistry("what_we_become");
   }
}
