package com.Harbinger.Spore.Client;

import com.Harbinger.Spore.Client.ArmorParts.AcidicAssassinPart;
import com.Harbinger.Spore.Client.ArmorParts.AcidicAssassinPartLeft;
import com.Harbinger.Spore.Client.ArmorParts.AcidicAssassinPartRight;
import com.Harbinger.Spore.Client.ArmorParts.BaseArmorRenderingBit;
import com.Harbinger.Spore.Client.ArmorParts.BileBlasterPart;
import com.Harbinger.Spore.Client.ArmorParts.BileBlasterPartLeft;
import com.Harbinger.Spore.Client.ArmorParts.BileBlasterPartRight;
import com.Harbinger.Spore.Client.ArmorParts.BodyArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.ComplexHandModelItem;
import com.Harbinger.Spore.Client.ArmorParts.ElytrumPart;
import com.Harbinger.Spore.Client.ArmorParts.EnchantingPart;
import com.Harbinger.Spore.Client.ArmorParts.HelmetArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.HelmetArmorPartEnchant;
import com.Harbinger.Spore.Client.ArmorParts.LeftArmArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.LeftArmArmorPartEnchant;
import com.Harbinger.Spore.Client.ArmorParts.LeftBootArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.LeftBootArmorPartEnchant;
import com.Harbinger.Spore.Client.ArmorParts.LeftLegArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.LeftLegArmorPartEnchant;
import com.Harbinger.Spore.Client.ArmorParts.LeftPCIArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.MistMakerPart;
import com.Harbinger.Spore.Client.ArmorParts.MistmakerPartLeft;
import com.Harbinger.Spore.Client.ArmorParts.MistmakerPartRight;
import com.Harbinger.Spore.Client.ArmorParts.PCIHandModelItem;
import com.Harbinger.Spore.Client.ArmorParts.RightArmArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.RightArmArmorPartEnchant;
import com.Harbinger.Spore.Client.ArmorParts.RightBootArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.RightBootArmorPartEnchant;
import com.Harbinger.Spore.Client.ArmorParts.RightLegArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.RightLegArmorPartEnchant;
import com.Harbinger.Spore.Client.ArmorParts.RightPCIArmorPart;
import com.Harbinger.Spore.Client.ArmorParts.SyringeGunArmorPartLeft;
import com.Harbinger.Spore.Client.ArmorParts.SyringeGunArmorPartRight;
import com.Harbinger.Spore.Client.ArmorParts.SyringeGunPart;
import com.Harbinger.Spore.Client.Models.AcidicAssasinArmModel;
import com.Harbinger.Spore.Client.Models.AcidicAssasinModel;
import com.Harbinger.Spore.Client.Models.BileBlasterArmModel;
import com.Harbinger.Spore.Client.Models.BileBlasterModel;
import com.Harbinger.Spore.Client.Models.GasMaskModel;
import com.Harbinger.Spore.Client.Models.MistmakerModel;
import com.Harbinger.Spore.Client.Models.MistmakerModelArm;
import com.Harbinger.Spore.Client.Models.PCI_Model;
import com.Harbinger.Spore.Client.Models.PCI_ModelL;
import com.Harbinger.Spore.Client.Models.RavenousJawModel;
import com.Harbinger.Spore.Client.Models.SyringeGunModel;
import com.Harbinger.Spore.Client.Models.SyringeGunModelArm;
import com.Harbinger.Spore.Client.Models.fleshArmorModel;
import com.Harbinger.Spore.Client.Models.lacedThornsModel;
import com.Harbinger.Spore.Client.Models.livingArmorMkModel;
import com.Harbinger.Spore.Client.Models.livingArmorModel;
import com.Harbinger.Spore.Client.Models.platedArmorModel;
import com.Harbinger.Spore.Core.Senchantments;
import com.Harbinger.Spore.Core.Sitems;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.enchantment.Enchantment;

public class ArmorModelList {
   private static final ResourceLocation psi_glow = new ResourceLocation("spore:textures/item/pci_gl.png");
   private static final ResourceLocation jaw_texture = new ResourceLocation("spore:textures/armor/ravenous_mouth.png");
   private static final ResourceLocation laced_thorns_texture = new ResourceLocation("spore:textures/armor/laced_thorns.png");
   private static final fleshArmorModel livingEntityfleshArmorModel = new fleshArmorModel();
   private static final platedArmorModel plated = new platedArmorModel();
   private static final GasMaskModel gasMaskModel = new GasMaskModel();
   private static final livingArmorModel livingArmorModel = new livingArmorModel();
   private static final livingArmorMkModel livingUpArmor = new livingArmorMkModel();
   private static final PCI_Model pci = new PCI_Model();
   private static final PCI_ModelL pciL = new PCI_ModelL();
   private static final RavenousJawModel jaw = new RavenousJawModel();
   private static final lacedThornsModel lacedThornsModel = new lacedThornsModel();
   private static final SyringeGunModel syringeGunModel = new SyringeGunModel();
   private static final SyringeGunModelArm syringeGunModelArm = new SyringeGunModelArm();
   private static final MistmakerModel mistmakerModel = new MistmakerModel();
   private static final MistmakerModelArm mistmakerModelArm = new MistmakerModelArm();
   private static final BileBlasterModel bileblaster = new BileBlasterModel();
   private static final AcidicAssasinModel acidicAssasinModel = new AcidicAssasinModel();
   private static final AcidicAssasinArmModel acidicAssasinArmModel = new AcidicAssasinArmModel();
   private static final BileBlasterArmModel bileblasterarm = new BileBlasterArmModel();
   private static final PCIHandModelItem RIGHT_PCI;
   private static final PCIHandModelItem LEFT_PCI;
   private static final SyringeGunPart RIGHT_SYRINGE_GUN;
   private static final SyringeGunPart LEFT_SYRINGE_GUN;
   private static final MistMakerPart RIGHT_MISTMAKER;
   private static final MistMakerPart LEFT_MISTMAKER;
   private static final BileBlasterPart RIGHT_BILEBLASTER;
   private static final BileBlasterPart LEFT_BILEBLASTER;
   private static final AcidicAssassinPart RIGHT_ACIDASSASIN;
   private static final AcidicAssassinPart LEFT_ACIDASSASIN;
   public static final List<ComplexHandModelItem> ITEM_RENDERING_BITS;
   private static final HelmetArmorPart LIVING_HELMET_PART;
   public static final BodyArmorPart LIVING_CHEST_PART;
   public static final RightArmArmorPart LIVING_RIGHT_ARM_PART;
   public static final LeftArmArmorPart LIVING_LEFT_ARM_PART;
   public static final BodyArmorPart LIVING_PELVIS_PART;
   public static final RightLegArmorPart LIVING_RIGHT_LEG_PART;
   public static final LeftLegArmorPart LIVING_LEFT_LEG_PART;
   public static final RightBootArmorPart LIVING_RIGHT_BOOT_PART;
   public static final LeftBootArmorPart LIVING_LEFT_BOOT_PART;
   private static final HelmetArmorPart PLATED_HELMET_PART;
   public static final BodyArmorPart PLATED_CHEST_PART;
   public static final RightArmArmorPart PLATED_RIGHT_ARM_PART;
   public static final LeftArmArmorPart PLATED_LEFT_ARM_PART;
   public static final RightLegArmorPart PLATED_RIGHT_LEG_PART;
   public static final LeftLegArmorPart PLATED_LEFT_LEG_PART;
   public static final RightBootArmorPart PLATED_RIGHT_BOOT_PART;
   public static final LeftBootArmorPart PLATED_LEFT_BOOT_PART;
   private static final HelmetArmorPart INF_HELMET_PART;
   public static final BodyArmorPart INF_CHEST_PART;
   public static final RightArmArmorPart INF_RIGHT_ARM_PART;
   public static final LeftArmArmorPart INF_LEFT_ARM_PART;
   public static final BodyArmorPart INF_PELVIS_PART;
   public static final RightLegArmorPart INF_RIGHT_LEG_PART;
   public static final LeftLegArmorPart INF_LEFT_LEG_PART;
   public static final RightBootArmorPart INF_RIGHT_BOOT_PART;
   public static final LeftBootArmorPart INF_LEFT_BOOT_PART;
   private static final HelmetArmorPart INF_UP_HELMET_PART;
   public static final BodyArmorPart INF_UP_CHEST_PART;
   public static final RightArmArmorPart INF_UP_RIGHT_ARM_PART;
   public static final LeftArmArmorPart INF_UP_LEFT_ARM_PART;
   public static final BodyArmorPart INF_UP_PELVIS_PART;
   public static final RightLegArmorPart INF_UP_RIGHT_LEG_PART;
   public static final LeftLegArmorPart INF_UP_LEFT_LEG_PART;
   public static final RightBootArmorPart INF_UP_RIGHT_BOOT_PART;
   public static final LeftBootArmorPart INF_UP_LEFT_BOOT_PART;
   private static final HelmetArmorPart GASMASK_PART;
   private static final ElytrumPart ELYTRUM;
   private static final RightPCIArmorPart PCI_RIGHT;
   private static final LeftPCIArmorPart PCI_LEFT;
   private static final SyringeGunArmorPartRight SYRINGE_GUN_RIGHT;
   private static final SyringeGunArmorPartLeft SYRINGE_GUN_LEFT;
   private static final MistmakerPartRight MIST_MAKER_RIGHT;
   private static final MistmakerPartLeft MIST_MAKER_LEFT;
   private static final BileBlasterPartRight BILE_BLASTER_RIGHT;
   private static final BileBlasterPartLeft BILE_BLASTER_LEFT;
   private static final AcidicAssassinPartRight ACIDIC_ASSASSIN_RIGHT;
   private static final AcidicAssassinPartLeft ACIDIC_ASSASSIN_LEFT;
   private static final List<Item> fleshBlackList;
   private static final HelmetArmorPartEnchant JAW_PART;
   private static final HelmetArmorPartEnchant THORNS_HELMET_PART;
   public static final RightArmArmorPartEnchant THORNS_RIGHT_ARM_PART;
   public static final LeftArmArmorPartEnchant THORNS_LEFT_ARM_PART;
   public static final RightLegArmorPartEnchant THORNS_RIGHT_LEG_PART;
   public static final LeftLegArmorPartEnchant THORNS_LEFT_LEG_PART;
   public static final RightBootArmorPartEnchant THORNS_RIGHT_BOOT_PART;
   public static final LeftBootArmorPartEnchant THORNS_LEFT_BOOT_PART;
   public static final List<BaseArmorRenderingBit> ARMOR_RENDERING_BITS;
   public static final List<EnchantingPart> ENCHANTING_RENDERING_BITS;

   static {
      RIGHT_PCI = new PCIHandModelItem(InteractionHand.MAIN_HAND, pci, pci.PCIBODY, 0.95F, -0.7F, -0.35F, 1.0F, -90.0F, 90.0F, 0.0F, psi_glow);
      LEFT_PCI = new PCIHandModelItem(InteractionHand.OFF_HAND, pci, pci.PCIBODY, -1.0F, -0.7F, -0.35F, 1.0F, -90.0F, 90.0F, 0.0F, psi_glow);
      RIGHT_SYRINGE_GUN = new SyringeGunPart(InteractionHand.MAIN_HAND, syringeGunModel, syringeGunModel.syringeGun, 0.95F, 0.5F, -1.25F, 1.0F, 0.0F, 0.0F, 180.0F);
      LEFT_SYRINGE_GUN = new SyringeGunPart(InteractionHand.OFF_HAND, syringeGunModel, syringeGunModel.syringeGun, -1.0F, 0.5F, -1.25F, 1.0F, 0.0F, 0.0F, 180.0F);
      RIGHT_MISTMAKER = new MistMakerPart(InteractionHand.MAIN_HAND, mistmakerModel, mistmakerModel.gun, 0.95F, 0.25F, -1.75F, 1.0F, 0.0F, 0.0F, 180.0F);
      LEFT_MISTMAKER = new MistMakerPart(InteractionHand.OFF_HAND, mistmakerModel, mistmakerModel.gun, -1.0F, 0.25F, -1.75F, 1.0F, 0.0F, 0.0F, 180.0F);
      RIGHT_BILEBLASTER = new BileBlasterPart(InteractionHand.MAIN_HAND, bileblaster, bileblaster.Bile_Blaster, 0.95F, 0.25F, -2.5F, 1.0F, 0.0F, 0.0F, 180.0F);
      LEFT_BILEBLASTER = new BileBlasterPart(InteractionHand.OFF_HAND, bileblaster, bileblaster.Bile_Blaster, -1.0F, 0.25F, -2.5F, 1.0F, 0.0F, 0.0F, 180.0F);
      RIGHT_ACIDASSASIN = new AcidicAssassinPart(InteractionHand.MAIN_HAND, acidicAssasinModel, acidicAssasinModel.Caspian, 0.95F, 0.25F, -2.5F, 1.0F, 0.0F, 0.0F, 180.0F);
      LEFT_ACIDASSASIN = new AcidicAssassinPart(InteractionHand.OFF_HAND, acidicAssasinModel, acidicAssasinModel.Caspian, -1.0F, 0.25F, -2.5F, 1.0F, 0.0F, 0.0F, 180.0F);
      ITEM_RENDERING_BITS = new ArrayList<>() {
         {
            this.add(ArmorModelList.RIGHT_PCI);
            this.add(ArmorModelList.LEFT_PCI);
            this.add(ArmorModelList.RIGHT_SYRINGE_GUN);
            this.add(ArmorModelList.LEFT_SYRINGE_GUN);
            this.add(ArmorModelList.RIGHT_MISTMAKER);
            this.add(ArmorModelList.LEFT_MISTMAKER);
            this.add(ArmorModelList.RIGHT_BILEBLASTER);
            this.add(ArmorModelList.LEFT_BILEBLASTER);
            this.add(ArmorModelList.RIGHT_ACIDASSASIN);
            this.add(ArmorModelList.LEFT_ACIDASSASIN);
         }
      };
      LIVING_HELMET_PART = new HelmetArmorPart(((Item)Sitems.LIVING_HELMET.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.headwear, 0.0F, 0.0F, 0.0F, 1.0F);
      LIVING_CHEST_PART = new BodyArmorPart(((Item)Sitems.LIVING_CHEST.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.body, 0.0F, 0.0F, 0.0F, 1.0F);
      LIVING_RIGHT_ARM_PART = new RightArmArmorPart(((Item)Sitems.LIVING_CHEST.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.rightArm, 0.3F, -0.125F, 0.0F, 1.0F);
      LIVING_LEFT_ARM_PART = new LeftArmArmorPart(((Item)Sitems.LIVING_CHEST.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.leftArm, -0.3F, -0.125F, 0.0F, 1.0F);
      LIVING_PELVIS_PART = new BodyArmorPart(((Item)Sitems.LIVING_PANTS.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.pelvis, 0.0F, 0.0F, 0.0F, 1.0F);
      LIVING_RIGHT_LEG_PART = new RightLegArmorPart(((Item)Sitems.LIVING_PANTS.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.rightLeg, 0.1F, -0.8F, 0.0F, 1.01F);
      LIVING_LEFT_LEG_PART = new LeftLegArmorPart(((Item)Sitems.LIVING_PANTS.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.leftLeg, -0.1F, -0.8F, 0.0F, 1.0F);
      LIVING_RIGHT_BOOT_PART = new RightBootArmorPart(((Item)Sitems.LIVING_BOOTS.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.rightBoot, 0.1F, -0.8F, 0.0F, 1.01F);
      LIVING_LEFT_BOOT_PART = new LeftBootArmorPart(((Item)Sitems.LIVING_BOOTS.get()).asItem(), () -> livingEntityfleshArmorModel, () -> livingEntityfleshArmorModel.leftBoot, -0.1F, -0.8F, 0.0F, 1.0F);
      PLATED_HELMET_PART = new HelmetArmorPart(((Item)Sitems.PLATED_HELMET.get()).asItem(), () -> plated, () -> plated.headwear, 0.0F, 0.0F, 0.0F, 1.0F);
      PLATED_CHEST_PART = new BodyArmorPart(((Item)Sitems.PLATED_CHEST.get()).asItem(), () -> plated, () -> plated.body, 0.0F, 0.0F, 0.0F, 1.0F);
      PLATED_RIGHT_ARM_PART = new RightArmArmorPart(((Item)Sitems.PLATED_CHEST.get()).asItem(), () -> plated, () -> plated.rightArm, 0.3F, -0.125F, 0.0F, 1.0F);
      PLATED_LEFT_ARM_PART = new LeftArmArmorPart(((Item)Sitems.PLATED_CHEST.get()).asItem(), () -> plated, () -> plated.leftArm, -0.3F, -0.125F, 0.0F, 1.0F);
      PLATED_RIGHT_LEG_PART = new RightLegArmorPart(((Item)Sitems.PLATED_PANTS.get()).asItem(), () -> plated, () -> plated.rightLeg, 0.1F, -0.8F, 0.0F, 1.01F);
      PLATED_LEFT_LEG_PART = new LeftLegArmorPart(((Item)Sitems.PLATED_PANTS.get()).asItem(), () -> plated, () -> plated.leftLeg, -0.1F, -0.8F, 0.0F, 1.0F);
      PLATED_RIGHT_BOOT_PART = new RightBootArmorPart(((Item)Sitems.PLATED_BOOTS.get()).asItem(), () -> plated, () -> plated.rightBoot, 0.1F, -0.8F, 0.0F, 1.01F);
      PLATED_LEFT_BOOT_PART = new LeftBootArmorPart(((Item)Sitems.PLATED_BOOTS.get()).asItem(), () -> plated, () -> plated.leftBoot, -0.1F, -0.8F, 0.0F, 1.0F);
      INF_HELMET_PART = new HelmetArmorPart(((Item)Sitems.INF_HELMET.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.headwear, 0.0F, 0.0F, 0.0F, 1.0F);
      INF_CHEST_PART = new BodyArmorPart(((Item)Sitems.INF_CHEST.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.body, 0.0F, 0.0F, 0.0F, 1.0F);
      INF_RIGHT_ARM_PART = new RightArmArmorPart(((Item)Sitems.INF_CHEST.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.rightArm, 0.3F, -0.125F, 0.0F, 1.0F);
      INF_LEFT_ARM_PART = new LeftArmArmorPart(((Item)Sitems.INF_CHEST.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.leftArm, -0.3F, -0.125F, 0.0F, 1.0F);
      INF_PELVIS_PART = new BodyArmorPart(((Item)Sitems.INF_PANTS.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.pelvis, 0.0F, 0.0F, 0.0F, 1.0F);
      INF_RIGHT_LEG_PART = new RightLegArmorPart(((Item)Sitems.INF_PANTS.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.rightLeg, 0.1F, -0.8F, 0.0F, 1.01F);
      INF_LEFT_LEG_PART = new LeftLegArmorPart(((Item)Sitems.INF_PANTS.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.leftLeg, -0.1F, -0.8F, 0.0F, 1.0F);
      INF_RIGHT_BOOT_PART = new RightBootArmorPart(((Item)Sitems.INF_BOOTS.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.rightBoot, 0.1F, -0.8F, 0.0F, 1.01F);
      INF_LEFT_BOOT_PART = new LeftBootArmorPart(((Item)Sitems.INF_BOOTS.get()).asItem(), () -> livingArmorModel, () -> livingArmorModel.leftBoot, -0.1F, -0.8F, 0.0F, 1.0F);
      INF_UP_HELMET_PART = new HelmetArmorPart(((Item)Sitems.INF_UP_HELMET.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.headwear, 0.0F, 0.0F, 0.0F, 1.0F);
      INF_UP_CHEST_PART = new BodyArmorPart(((Item)Sitems.INF_UP_CHESTPLATE.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.body, 0.0F, 0.0F, 0.0F, 1.0F);
      INF_UP_RIGHT_ARM_PART = new RightArmArmorPart(((Item)Sitems.INF_UP_CHESTPLATE.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.rightArm, 0.3F, -0.125F, 0.0F, 1.0F);
      INF_UP_LEFT_ARM_PART = new LeftArmArmorPart(((Item)Sitems.INF_UP_CHESTPLATE.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.leftArm, -0.3F, -0.125F, 0.0F, 1.0F);
      INF_UP_PELVIS_PART = new BodyArmorPart(((Item)Sitems.INF_UP_PANTS.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.pelvis, 0.0F, 0.0F, 0.0F, 1.0F);
      INF_UP_RIGHT_LEG_PART = new RightLegArmorPart(((Item)Sitems.INF_UP_PANTS.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.rightLeg, 0.1F, -0.8F, 0.0F, 1.01F);
      INF_UP_LEFT_LEG_PART = new LeftLegArmorPart(((Item)Sitems.INF_UP_PANTS.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.leftLeg, -0.1F, -0.8F, 0.0F, 1.0F);
      INF_UP_RIGHT_BOOT_PART = new RightBootArmorPart(((Item)Sitems.INF_UP_BOOTS.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.rightBoot, 0.1F, -0.8F, 0.0F, 1.01F);
      INF_UP_LEFT_BOOT_PART = new LeftBootArmorPart(((Item)Sitems.INF_UP_BOOTS.get()).asItem(), () -> livingUpArmor, () -> livingUpArmor.leftBoot, -0.1F, -0.8F, 0.0F, 1.0F);
      GASMASK_PART = new HelmetArmorPart(((Item)Sitems.GAS_MASK.get()).asItem(), () -> gasMaskModel, () -> gasMaskModel.GasMask, 0.0F, 0.0F, 0.0F, 1.0F);
      ELYTRUM = new ElytrumPart(((Item)Sitems.R_ELYTRON.get()).asItem(), 0.0F, 0.0F, -0.1F);
      PCI_RIGHT = new RightPCIArmorPart(() -> pci, () -> pci.PCIBODY, psi_glow);
      PCI_LEFT = new LeftPCIArmorPart(() -> pciL, () -> pciL.PCIBODY, psi_glow);
      SYRINGE_GUN_RIGHT = new SyringeGunArmorPartRight(syringeGunModelArm, () -> syringeGunModelArm, () -> syringeGunModelArm.syringeGun, 0.2F, 0.5F, 0.1F, 0.4F);
      SYRINGE_GUN_LEFT = new SyringeGunArmorPartLeft(syringeGunModelArm, () -> syringeGunModelArm, () -> syringeGunModelArm.syringeGun, 0.1F, 0.5F, 0.1F, 0.4F);
      MIST_MAKER_RIGHT = new MistmakerPartRight(() -> mistmakerModelArm, () -> mistmakerModelArm.gun, 0.1F, 1.2F, 0.3F, 0.4F);
      MIST_MAKER_LEFT = new MistmakerPartLeft(() -> mistmakerModelArm, () -> mistmakerModelArm.gun, 0.0F, 1.2F, 0.3F, 0.4F);
      BILE_BLASTER_RIGHT = new BileBlasterPartRight(() -> bileblasterarm, () -> bileblasterarm.Bile_Blaster, 0.1F, 0.6F, 0.0F, 0.4F);
      BILE_BLASTER_LEFT = new BileBlasterPartLeft(() -> bileblasterarm, () -> bileblasterarm.Bile_Blaster, 0.0F, 0.6F, 0.0F, 0.4F);
      ACIDIC_ASSASSIN_RIGHT = new AcidicAssassinPartRight(() -> acidicAssasinArmModel, () -> acidicAssasinArmModel.Caspian, 0.1F, 0.6F, 0.0F, 0.4F);
      ACIDIC_ASSASSIN_LEFT = new AcidicAssassinPartLeft(() -> acidicAssasinArmModel, () -> acidicAssasinArmModel.Caspian, 0.15F, 0.6F, 0.0F, 0.4F);
      fleshBlackList = List.of((Item)Sitems.LIVING_HELMET.get(), (Item)Sitems.LIVING_CHEST.get(), (Item)Sitems.LIVING_PANTS.get(), (Item)Sitems.LIVING_BOOTS.get());
      JAW_PART = new HelmetArmorPartEnchant(() -> jaw, () -> jaw.jaw, 0.0F, 0.0F, 0.0F, 1.0F, (Enchantment)Senchantments.VORACIOUS_MAW.get(), jaw_texture, List.of());
      THORNS_HELMET_PART = new HelmetArmorPartEnchant(() -> lacedThornsModel, () -> lacedThornsModel.head, 0.0F, 0.0F, 0.0F, 1.0F, (Enchantment)Senchantments.SERRATED_THORNS.get(), laced_thorns_texture, fleshBlackList);
      THORNS_RIGHT_ARM_PART = new RightArmArmorPartEnchant(() -> lacedThornsModel, () -> lacedThornsModel.rightDarm, 0.3F, -0.125F, 0.0F, 1.0F, (Enchantment)Senchantments.SERRATED_THORNS.get(), laced_thorns_texture, fleshBlackList);
      THORNS_LEFT_ARM_PART = new LeftArmArmorPartEnchant(() -> lacedThornsModel, () -> lacedThornsModel.leftDarm, -0.3F, -0.125F, 0.0F, 1.0F, (Enchantment)Senchantments.SERRATED_THORNS.get(), laced_thorns_texture, fleshBlackList);
      THORNS_RIGHT_LEG_PART = new RightLegArmorPartEnchant(() -> lacedThornsModel, () -> lacedThornsModel.rightDleg, 0.1F, -0.8F, 0.0F, 1.01F, (Enchantment)Senchantments.SERRATED_THORNS.get(), laced_thorns_texture, fleshBlackList);
      THORNS_LEFT_LEG_PART = new LeftLegArmorPartEnchant(() -> lacedThornsModel, () -> lacedThornsModel.leftDleg, -0.1F, -0.8F, 0.0F, 1.0F, (Enchantment)Senchantments.SERRATED_THORNS.get(), laced_thorns_texture, fleshBlackList);
      THORNS_RIGHT_BOOT_PART = new RightBootArmorPartEnchant(() -> lacedThornsModel, () -> lacedThornsModel.rightDboot, 0.1F, -0.8F, 0.0F, 1.01F, (Enchantment)Senchantments.SERRATED_THORNS.get(), laced_thorns_texture, fleshBlackList);
      THORNS_LEFT_BOOT_PART = new LeftBootArmorPartEnchant(() -> lacedThornsModel, () -> lacedThornsModel.leftDboot, -0.1F, -0.8F, 0.0F, 1.0F, (Enchantment)Senchantments.SERRATED_THORNS.get(), laced_thorns_texture, fleshBlackList);
      ARMOR_RENDERING_BITS = new ArrayList<>() {
         {
            this.add(ArmorModelList.LIVING_HELMET_PART);
            this.add(ArmorModelList.LIVING_CHEST_PART);
            this.add(ArmorModelList.LIVING_RIGHT_ARM_PART);
            this.add(ArmorModelList.LIVING_LEFT_ARM_PART);
            this.add(ArmorModelList.LIVING_PELVIS_PART);
            this.add(ArmorModelList.LIVING_RIGHT_LEG_PART);
            this.add(ArmorModelList.LIVING_LEFT_LEG_PART);
            this.add(ArmorModelList.LIVING_RIGHT_BOOT_PART);
            this.add(ArmorModelList.LIVING_LEFT_BOOT_PART);
            this.add(ArmorModelList.PLATED_HELMET_PART);
            this.add(ArmorModelList.PLATED_CHEST_PART);
            this.add(ArmorModelList.PLATED_RIGHT_ARM_PART);
            this.add(ArmorModelList.PLATED_LEFT_ARM_PART);
            this.add(ArmorModelList.PLATED_RIGHT_LEG_PART);
            this.add(ArmorModelList.PLATED_LEFT_LEG_PART);
            this.add(ArmorModelList.PLATED_RIGHT_BOOT_PART);
            this.add(ArmorModelList.PLATED_LEFT_BOOT_PART);
            this.add(ArmorModelList.INF_HELMET_PART);
            this.add(ArmorModelList.INF_CHEST_PART);
            this.add(ArmorModelList.INF_RIGHT_ARM_PART);
            this.add(ArmorModelList.INF_LEFT_ARM_PART);
            this.add(ArmorModelList.INF_PELVIS_PART);
            this.add(ArmorModelList.INF_RIGHT_LEG_PART);
            this.add(ArmorModelList.INF_LEFT_LEG_PART);
            this.add(ArmorModelList.INF_RIGHT_BOOT_PART);
            this.add(ArmorModelList.INF_LEFT_BOOT_PART);
            this.add(ArmorModelList.INF_UP_HELMET_PART);
            this.add(ArmorModelList.INF_UP_CHEST_PART);
            this.add(ArmorModelList.INF_UP_RIGHT_ARM_PART);
            this.add(ArmorModelList.INF_UP_LEFT_ARM_PART);
            this.add(ArmorModelList.INF_UP_PELVIS_PART);
            this.add(ArmorModelList.INF_UP_RIGHT_LEG_PART);
            this.add(ArmorModelList.INF_UP_LEFT_LEG_PART);
            this.add(ArmorModelList.INF_UP_RIGHT_BOOT_PART);
            this.add(ArmorModelList.INF_UP_LEFT_BOOT_PART);
            this.add(ArmorModelList.ELYTRUM);
            this.add(ArmorModelList.GASMASK_PART);
            this.add(ArmorModelList.PCI_RIGHT);
            this.add(ArmorModelList.PCI_LEFT);
            this.add(ArmorModelList.SYRINGE_GUN_LEFT);
            this.add(ArmorModelList.SYRINGE_GUN_RIGHT);
            this.add(ArmorModelList.MIST_MAKER_LEFT);
            this.add(ArmorModelList.MIST_MAKER_RIGHT);
            this.add(ArmorModelList.BILE_BLASTER_LEFT);
            this.add(ArmorModelList.BILE_BLASTER_RIGHT);
            this.add(ArmorModelList.ACIDIC_ASSASSIN_RIGHT);
            this.add(ArmorModelList.ACIDIC_ASSASSIN_LEFT);
         }
      };
      ENCHANTING_RENDERING_BITS = new ArrayList<>() {
         {
            this.add(ArmorModelList.JAW_PART);
            this.add(ArmorModelList.THORNS_HELMET_PART);
            this.add(ArmorModelList.THORNS_RIGHT_ARM_PART);
            this.add(ArmorModelList.THORNS_LEFT_ARM_PART);
            this.add(ArmorModelList.THORNS_RIGHT_LEG_PART);
            this.add(ArmorModelList.THORNS_LEFT_LEG_PART);
            this.add(ArmorModelList.THORNS_RIGHT_BOOT_PART);
            this.add(ArmorModelList.THORNS_LEFT_BOOT_PART);
         }
      };
   }
}
