package com.Harbinger.Spore.Client;

import com.Harbinger.Spore.Client.Models.GazenbrecherModel;
import com.Harbinger.Spore.Client.Models.GrakensenkerModel;
import com.Harbinger.Spore.Client.Models.HindieModel;
import com.Harbinger.Spore.Client.Models.HohlfresserSeg1Model;
import com.Harbinger.Spore.Client.Models.HohlfresserSeg2Model;
import com.Harbinger.Spore.Client.Models.HohlfresserSeg3Model;
import com.Harbinger.Spore.Client.Models.HowitzerModel;
import com.Harbinger.Spore.Client.Models.LeviathanMiddleSegment;
import com.Harbinger.Spore.Client.Models.LeviathanModel;
import com.Harbinger.Spore.Client.Models.LeviathanTailModel;
import com.Harbinger.Spore.Client.Models.SiegerModel;
import com.Harbinger.Spore.Client.Models.StahlmorderModel;
import com.Harbinger.Spore.Client.Models.adaptedwormsegment1;
import com.Harbinger.Spore.Client.Models.adaptedwormsegment2;
import com.Harbinger.Spore.Client.Models.adaptedwormsegment3;
import com.Harbinger.Spore.Client.Models.adaptedwormtail;
import com.Harbinger.Spore.Client.Models.hohlfresserHeadModel;
import com.Harbinger.Spore.Client.Models.hohlfresserHeadModelAdapted;
import com.Harbinger.Spore.Client.Models.hohlfresserTailModel;
import java.util.ArrayList;
import java.util.List;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class CalamityPartsHandeling {
   private static final SiegerModel siegerModel = new SiegerModel();
   private static final GazenbrecherModel gazenModel = new GazenbrecherModel();
   private static final HindieModel hindieModel = new HindieModel();
   private static final HowitzerModel howiModel = new HowitzerModel();
   private static final hohlfresserHeadModel worm_headModel = new hohlfresserHeadModel();
   private static final HohlfresserSeg1Model worm_seg1Model = new HohlfresserSeg1Model();
   private static final HohlfresserSeg2Model worm_seg2Model = new HohlfresserSeg2Model();
   private static final HohlfresserSeg3Model worm_seg3Model = new HohlfresserSeg3Model();
   private static final hohlfresserTailModel worm_tailModel = new hohlfresserTailModel();
   private static final GrakensenkerModel grakensenkerModel = new GrakensenkerModel();
   private static final StahlmorderModel stahlmorderModel = new StahlmorderModel();
   private static final LeviathanModel leviathanModel = new LeviathanModel();
   private static final LeviathanMiddleSegment leviathanSegModel = new LeviathanMiddleSegment();
   private static final LeviathanTailModel leviathanTailModel = new LeviathanTailModel();
   private static final hohlfresserHeadModelAdapted worm_ada_headModel = new hohlfresserHeadModelAdapted();
   private static final adaptedwormsegment1 worm_ada_seg1Model = new adaptedwormsegment1();
   private static final adaptedwormsegment2 worm_ada_seg2Model = new adaptedwormsegment2();
   private static final adaptedwormsegment3 worm_ada_seg3Model = new adaptedwormsegment3();
   private static final adaptedwormtail worm_ada_tailModel = new adaptedwormtail();
   private static final ResourceLocation DEFAULT_SIEGER = new ResourceLocation("spore", "textures/entity/sieger.png");
   private static final ResourceLocation ADAPTED_SIEGER = new ResourceLocation("spore", "textures/entity/war_sieger.png");
   private static final ResourceLocation DEFAULT_GAZEN = new ResourceLocation("spore", "textures/entity/gazen.png");
   private static final ResourceLocation ADAPTED_GAZEN = new ResourceLocation("spore", "textures/entity/burned_gazen.png");
   private static final ResourceLocation DEFAULT_HINDEN = new ResourceLocation("spore", "textures/entity/hindie.png");
   private static final ResourceLocation ADAPTED_HINDEN = new ResourceLocation("spore", "textures/entity/hindie_adapted.png");
   private static final ResourceLocation DEFAULT_HOWI = new ResourceLocation("spore", "textures/entity/howitzer.png");
   private static final ResourceLocation ADAPTED_HOWI = new ResourceLocation("spore", "textures/entity/nuclear_howitzer.png");
   private static final ResourceLocation HOHLHEAD = new ResourceLocation("spore", "textures/entity/hohl_head.png");
   private static final ResourceLocation HOHL_SEG = new ResourceLocation("spore", "textures/entity/hohl/hohl_seg1.png");
   private static final ResourceLocation HOHL_SHARP_SEG = new ResourceLocation("spore", "textures/entity/hohl/hohl_seg2.png");
   private static final ResourceLocation HOHL_ORGAN_SEG = new ResourceLocation("spore", "textures/entity/hohl/hohl_seg3.png");
   private static final ResourceLocation HOHL_ADAPTED = new ResourceLocation("spore", "textures/entity/hohl/hohl_head_adapted.png");
   private static final ResourceLocation HOHL_SEG1_ADA = new ResourceLocation("spore", "textures/entity/hohl/adaptedwormsegment1.png");
   private static final ResourceLocation HOHL_SEG2_ADA = new ResourceLocation("spore", "textures/entity/hohl/adaptedwormsegment2.png");
   private static final ResourceLocation HOHL_SEG3_ADA = new ResourceLocation("spore", "textures/entity/hohl/adaptedwormsegment3.png");
   private static final ResourceLocation GRAKEN = new ResourceLocation("spore", "textures/entity/graken.png");
   private static final ResourceLocation STAHL = new ResourceLocation("spore", "textures/entity/stalh.png");
   private static final ResourceLocation LEVIATHAN = new ResourceLocation("spore", "textures/entity/leviathan.png");
   private static final ResourceLocation LEVIATHAN_TAIL = new ResourceLocation("spore", "textures/entity/leviathan_tail.png");
   public static final Part SIEGER_BODY;
   public static final Part SIEGER_JAW;
   public static final Part SIEGER_RIGHT_LEG;
   public static final Part SIEGER_LEFT_LEG;
   public static final Part SIEGER_BACK_RIGHT_LEG;
   public static final Part SIEGER_BACK_LEFT_LEG;
   public static final Part SIEGER_TAIL;
   public static final Part GAZEN_TAIL;
   public static final Part GAZEN_HEAD;
   public static final Part GAZEN_RIGHT_LEG;
   public static final Part GAZEN_LEFT_LEG;
   public static final Part LICKER;
   public static final Part HINDEN_FRONT;
   public static final Part HINDEN_BACK;
   public static final Part MAW;
   public static final Part RIGHT_CANNON;
   public static final Part LEFT_CANNON;
   public static final Part HOWI_CANNON1;
   public static final Part HOWI_CANNON2;
   public static final Part HOWI_CANNON3;
   public static final Part HOWI_LEFT_LEG;
   public static final Part HOWI_RIGHT_LEG;
   public static final Part HOWI_LEFT_ARM;
   public static final Part HOWI_RIGHT_ARM;
   public static final Part HOWI_SACK;
   public static final Part HOHL_JAW;
   public static final Part HOHL_HEAD;
   public static final Part HOHL_SEG1;
   public static final Part HOHL_SEG2;
   public static final Part HOHL_SEG3;
   public static final Part HOHL_TAIL;
   public static final Part GRAKEN_BODY;
   public static final Part GRAKEN_BACK_MAW;
   public static final Part GRAKEN_FRONT_MAW;
   public static final Part GRAKEN_HINGE;
   public static final Part STAHL_RIGHT_LEG;
   public static final Part STAHL_LEFT_LEG;
   public static final Part STAHL_BLADE_ARM;
   public static final Part STAHL_ARM_ARM;
   public static final Part STAHL_ARM_ARM2;
   public static final Part STAHL_MOUTH;
   public static final Part LEVIATHAN_BODY;
   public static final Part LEVIATHAN_SEGMENT;
   public static final Part LEVI_TAIL;
   public static final Part LEVI_RIGHT_JAW;
   public static final Part LEVI_LEFT_JAW;
   public static final Part HOHL_ADA_JAW;
   public static final Part HOHL_ADA_HEAD;
   public static final Part HOHL_ADA_SEG1;
   public static final Part HOHL_ADA_SEG2;
   public static final Part HOHL_ADA_SEG3;
   public static final Part HOHL_ADA_TAIL;
   public static final List<Part> getParts;

   public static Part getPart(int value) {
      return (Part)getParts.stream().filter((p) -> p.id == value).findFirst().orElse(SIEGER_BODY);
   }

   static {
      SIEGER_BODY = new Part(0, List.of(siegerModel.mainbody, siegerModel.mainbody2), 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, DEFAULT_SIEGER, ADAPTED_SIEGER);
      SIEGER_JAW = new Part(1, List.of(siegerModel.jaw), -1.0F, -0.5F, 0.0F, -30.0F, 0.0F, 0.0F, DEFAULT_SIEGER, ADAPTED_SIEGER);
      SIEGER_RIGHT_LEG = new Part(2, List.of(siegerModel.RightLegJointY), 0.0F, -0.5F, 2.0F, 0.0F, 0.0F, 0.0F, DEFAULT_SIEGER, ADAPTED_SIEGER);
      SIEGER_LEFT_LEG = new Part(3, List.of(siegerModel.LeftLegJointY), 0.0F, -0.5F, -2.0F, 0.0F, 0.0F, 0.0F, DEFAULT_SIEGER, ADAPTED_SIEGER);
      SIEGER_BACK_RIGHT_LEG = new Part(4, List.of(siegerModel.BackRightLeg), 4.0F, 0.0F, -1.0F, 0.0F, 0.0F, 0.0F, DEFAULT_SIEGER, ADAPTED_SIEGER);
      SIEGER_BACK_LEFT_LEG = new Part(5, List.of(siegerModel.BackLeftLeg), 4.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, DEFAULT_SIEGER, ADAPTED_SIEGER);
      SIEGER_TAIL = new Part(6, List.of(siegerModel.tail), 1.5F, -3.0F, 0.0F, -90.0F, 90.0F, 0.0F, DEFAULT_SIEGER, ADAPTED_SIEGER);
      GAZEN_TAIL = new Part(7, List.of(gazenModel.Segment4), 2.0F, 0.0F, 1.0F, 0.0F, 30.0F, 90.0F, DEFAULT_GAZEN, ADAPTED_GAZEN);
      GAZEN_HEAD = new Part(8, List.of(gazenModel.TopJaw, gazenModel.RightJaw, gazenModel.LeftJaw), 1.0F, 0.75F, 0.0F, -90.0F, 0.0F, 0.0F, DEFAULT_GAZEN, ADAPTED_GAZEN);
      GAZEN_RIGHT_LEG = new Part(9, List.of(gazenModel.RightLeg), 0.0F, 0.25F, 1.25F, 0.0F, 0.0F, 0.0F, DEFAULT_GAZEN, ADAPTED_GAZEN);
      GAZEN_LEFT_LEG = new Part(10, List.of(gazenModel.LeftLeg), 0.0F, 0.75F, -1.25F, 0.0F, 0.0F, 0.0F, DEFAULT_GAZEN, ADAPTED_GAZEN);
      LICKER = new Part(11, List.of(gazenModel.Licker1), -1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, DEFAULT_GAZEN, ADAPTED_GAZEN);
      HINDEN_FRONT = new Part(12, List.of(hindieModel.FrontSection), -3.5F, -4.0F, 0.0F, -45.0F, 0.0F, 0.0F, DEFAULT_HINDEN, ADAPTED_HINDEN);
      HINDEN_BACK = new Part(13, List.of(hindieModel.BackSectionSection), 3.5F, -4.0F, 0.0F, 45.0F, 0.0F, 0.0F, DEFAULT_HINDEN, ADAPTED_HINDEN);
      MAW = new Part(14, List.of(hindieModel.Maw), 0.0F, -4.0F, 0.0F, 180.0F, 0.0F, 0.0F, DEFAULT_HINDEN, ADAPTED_HINDEN);
      RIGHT_CANNON = new Part(15, List.of(hindieModel.RightCannon), 0.3F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, DEFAULT_HINDEN, ADAPTED_HINDEN);
      LEFT_CANNON = new Part(16, List.of(hindieModel.LeftCannon), 0.3F, 0.0F, 6.0F, 0.0F, 0.0F, 0.0F, DEFAULT_HINDEN, ADAPTED_HINDEN);
      HOWI_CANNON1 = new Part(17, List.of(howiModel.Cannon3), -0.75F, 0.5F, 1.0F, 0.0F, 0.0F, 0.0F, DEFAULT_HOWI, ADAPTED_HOWI);
      HOWI_CANNON2 = new Part(18, List.of(howiModel.Cannon6), -0.75F, 0.5F, 1.0F, 0.0F, 0.0F, 0.0F, DEFAULT_HOWI, ADAPTED_HOWI);
      HOWI_CANNON3 = new Part(19, List.of(howiModel.Cannon9), -0.75F, 0.5F, 1.0F, 0.0F, 0.0F, 0.0F, DEFAULT_HOWI, ADAPTED_HOWI);
      HOWI_LEFT_LEG = new Part(20, List.of(howiModel.LeftLeg), 0.0F, 1.0F, 1.5F, 90.0F, 0.0F, 90.0F, DEFAULT_HOWI, ADAPTED_HOWI);
      HOWI_RIGHT_LEG = new Part(21, List.of(howiModel.RightLeg), 0.5F, -0.5F, -2.5F, 90.0F, 0.0F, 90.0F, DEFAULT_HOWI, ADAPTED_HOWI);
      HOWI_LEFT_ARM = new Part(22, List.of(howiModel.LeftArm), -3.5F, 0.0F, 3.5F, 0.0F, 0.0F, 90.0F, DEFAULT_HOWI, ADAPTED_HOWI);
      HOWI_RIGHT_ARM = new Part(23, List.of(howiModel.RightArm), 3.5F, 0.0F, -2.0F, 0.0F, 0.0F, 90.0F, DEFAULT_HOWI, ADAPTED_HOWI);
      HOWI_SACK = new Part(24, List.of(howiModel.Tumor7), 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, DEFAULT_HOWI, ADAPTED_HOWI);
      HOHL_JAW = new Part(25, List.of(worm_headModel.TrueHead), -3.5F, 0.0F, 0.0F, -90.0F, 0.0F, 0.0F, HOHLHEAD, HOHLHEAD);
      HOHL_HEAD = new Part(26, List.of(worm_headModel.Middle), 2.25F, 0.0F, 0.0F, -90.0F, 0.0F, 0.0F, HOHLHEAD, HOHLHEAD);
      HOHL_SEG1 = new Part(27, List.of(worm_seg1Model.hohl_seg), 0.0F, 0.5F, 0.0F, 0.0F, 0.0F, 0.0F, HOHL_SEG, HOHL_SEG);
      HOHL_SEG2 = new Part(28, List.of(worm_seg2Model.hohl_seg), 0.0F, 0.5F, 0.0F, 0.0F, 0.0F, 0.0F, HOHL_SHARP_SEG, HOHL_SHARP_SEG);
      HOHL_SEG3 = new Part(29, List.of(worm_seg3Model.hohl_seg), 0.0F, 0.5F, 0.0F, 0.0F, 0.0F, 0.0F, HOHL_ORGAN_SEG, HOHL_ORGAN_SEG);
      HOHL_TAIL = new Part(30, List.of(worm_tailModel.tail), 0.0F, 0.0F, 0.5F, 0.0F, 0.0F, 0.0F, HOHL_SEG, HOHL_SEG);
      GRAKEN_BODY = new Part(31, List.of(grakensenkerModel.body2, grakensenkerModel.FrontSeg2CorpseDetails, grakensenkerModel.CenterCorpseDetails6, grakensenkerModel.CenterCorpseDetails3), 3.0F, 2.0F, 1.5F, 0.0F, 0.0F, 0.0F, GRAKEN, GRAKEN);
      GRAKEN_BACK_MAW = new Part(32, List.of(grakensenkerModel.head), -1.5F, -2.5F, 0.0F, 0.0F, 0.0F, 0.0F, GRAKEN, GRAKEN);
      GRAKEN_FRONT_MAW = new Part(33, List.of(grakensenkerModel.FrontJaw), -1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, GRAKEN, GRAKEN);
      GRAKEN_HINGE = new Part(34, List.of(grakensenkerModel.BackBodyMouthProtection), 6.0F, -6.0F, 0.0F, 0.0F, 0.0F, 0.0F, GRAKEN, GRAKEN);
      STAHL_RIGHT_LEG = new Part(35, List.of(stahlmorderModel.Rightleg), 0.0F, -1.5F, -1.0F, 0.0F, 0.0F, 0.0F, STAHL, STAHL);
      STAHL_LEFT_LEG = new Part(36, List.of(stahlmorderModel.Leftleg), 0.0F, -1.5F, 1.0F, 0.0F, 0.0F, 0.0F, STAHL, STAHL);
      STAHL_BLADE_ARM = new Part(37, List.of(stahlmorderModel.Evilshoulder), -1.5F, -2.5F, 3.5F, 30.0F, 0.0F, 0.0F, STAHL, STAHL);
      STAHL_ARM_ARM = new Part(38, List.of(stahlmorderModel.UpperRightarm), 0.0F, -1.0F, -2.0F, 0.0F, 0.0F, 0.0F, STAHL, STAHL);
      STAHL_ARM_ARM2 = new Part(39, List.of(stahlmorderModel.LowerRightarm), 0.0F, 1.0F, -2.0F, 0.0F, 0.0F, 0.0F, STAHL, STAHL);
      STAHL_MOUTH = new Part(40, List.of(stahlmorderModel.Mouth), -1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, STAHL, STAHL);
      LEVIATHAN_BODY = new Part(41, List.of(leviathanModel.Base, leviathanModel.details, leviathanModel.acidSacks, leviathanModel.Tumors, leviathanModel.Tumors2), 4.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, LEVIATHAN, LEVIATHAN);
      LEVIATHAN_SEGMENT = new Part(42, List.of(leviathanSegModel.LeviathanAbdomen), 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, LEVIATHAN_TAIL, LEVIATHAN_TAIL);
      LEVI_TAIL = new Part(43, List.of(leviathanTailModel.LeviathanAbdomen), 0.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F, LEVIATHAN_TAIL, LEVIATHAN_TAIL);
      LEVI_RIGHT_JAW = new Part(44, List.of(leviathanModel.RightJaw), -1.0F, -2.0F, -1.0F, 0.0F, 0.0F, 90.0F, LEVIATHAN, LEVIATHAN);
      LEVI_LEFT_JAW = new Part(45, List.of(leviathanModel.LeftJaw), -1.0F, -2.0F, 1.0F, 0.0F, 0.0F, 90.0F, LEVIATHAN, LEVIATHAN);
      HOHL_ADA_JAW = new Part(46, List.of(worm_ada_headModel.TrueHead), -3.5F, 0.0F, 0.0F, -90.0F, 0.0F, 0.0F, HOHL_ADAPTED, HOHL_ADAPTED);
      HOHL_ADA_HEAD = new Part(47, List.of(worm_ada_headModel.Middle), 2.25F, 0.0F, 0.0F, -90.0F, 0.0F, 0.0F, HOHL_ADAPTED, HOHL_ADAPTED);
      HOHL_ADA_SEG1 = new Part(48, List.of(worm_ada_seg1Model.hohl_seg), 0.0F, 0.5F, 0.0F, 0.0F, 0.0F, 0.0F, HOHL_SEG1_ADA, HOHL_SEG1_ADA);
      HOHL_ADA_SEG2 = new Part(49, List.of(worm_ada_seg2Model.hohl_seg), 0.0F, 0.5F, 0.0F, 0.0F, 0.0F, 0.0F, HOHL_SEG2_ADA, HOHL_SEG2_ADA);
      HOHL_ADA_SEG3 = new Part(50, List.of(worm_ada_seg3Model.hohl_seg), 0.0F, 0.5F, 0.0F, 0.0F, 0.0F, 0.0F, HOHL_SEG3_ADA, HOHL_SEG3_ADA);
      HOHL_ADA_TAIL = new Part(51, List.of(worm_tailModel.tail), 0.0F, 0.0F, 0.5F, 0.0F, 0.0F, 0.0F, HOHL_SEG1_ADA, HOHL_SEG1_ADA);
      getParts = new ArrayList() {
         {
            this.add(CalamityPartsHandeling.SIEGER_BODY);
            this.add(CalamityPartsHandeling.SIEGER_JAW);
            this.add(CalamityPartsHandeling.SIEGER_RIGHT_LEG);
            this.add(CalamityPartsHandeling.SIEGER_LEFT_LEG);
            this.add(CalamityPartsHandeling.SIEGER_BACK_RIGHT_LEG);
            this.add(CalamityPartsHandeling.SIEGER_BACK_LEFT_LEG);
            this.add(CalamityPartsHandeling.SIEGER_TAIL);
            this.add(CalamityPartsHandeling.GAZEN_TAIL);
            this.add(CalamityPartsHandeling.GAZEN_HEAD);
            this.add(CalamityPartsHandeling.GAZEN_RIGHT_LEG);
            this.add(CalamityPartsHandeling.GAZEN_LEFT_LEG);
            this.add(CalamityPartsHandeling.LICKER);
            this.add(CalamityPartsHandeling.HINDEN_FRONT);
            this.add(CalamityPartsHandeling.HINDEN_BACK);
            this.add(CalamityPartsHandeling.MAW);
            this.add(CalamityPartsHandeling.RIGHT_CANNON);
            this.add(CalamityPartsHandeling.LEFT_CANNON);
            this.add(CalamityPartsHandeling.HOWI_CANNON1);
            this.add(CalamityPartsHandeling.HOWI_CANNON2);
            this.add(CalamityPartsHandeling.HOWI_CANNON3);
            this.add(CalamityPartsHandeling.HOWI_LEFT_LEG);
            this.add(CalamityPartsHandeling.HOWI_RIGHT_LEG);
            this.add(CalamityPartsHandeling.HOWI_LEFT_ARM);
            this.add(CalamityPartsHandeling.HOWI_RIGHT_ARM);
            this.add(CalamityPartsHandeling.HOWI_SACK);
            this.add(CalamityPartsHandeling.HOHL_JAW);
            this.add(CalamityPartsHandeling.HOHL_HEAD);
            this.add(CalamityPartsHandeling.HOHL_SEG1);
            this.add(CalamityPartsHandeling.HOHL_SEG2);
            this.add(CalamityPartsHandeling.HOHL_SEG3);
            this.add(CalamityPartsHandeling.HOHL_TAIL);
            this.add(CalamityPartsHandeling.GRAKEN_BODY);
            this.add(CalamityPartsHandeling.GRAKEN_BACK_MAW);
            this.add(CalamityPartsHandeling.GRAKEN_FRONT_MAW);
            this.add(CalamityPartsHandeling.GRAKEN_HINGE);
            this.add(CalamityPartsHandeling.STAHL_RIGHT_LEG);
            this.add(CalamityPartsHandeling.STAHL_LEFT_LEG);
            this.add(CalamityPartsHandeling.STAHL_BLADE_ARM);
            this.add(CalamityPartsHandeling.STAHL_ARM_ARM);
            this.add(CalamityPartsHandeling.STAHL_ARM_ARM2);
            this.add(CalamityPartsHandeling.STAHL_MOUTH);
            this.add(CalamityPartsHandeling.LEVIATHAN_BODY);
            this.add(CalamityPartsHandeling.LEVIATHAN_SEGMENT);
            this.add(CalamityPartsHandeling.LEVI_TAIL);
            this.add(CalamityPartsHandeling.LEVI_RIGHT_JAW);
            this.add(CalamityPartsHandeling.LEVI_LEFT_JAW);
            this.add(CalamityPartsHandeling.HOHL_ADA_JAW);
            this.add(CalamityPartsHandeling.HOHL_ADA_HEAD);
            this.add(CalamityPartsHandeling.HOHL_ADA_SEG1);
            this.add(CalamityPartsHandeling.HOHL_ADA_SEG2);
            this.add(CalamityPartsHandeling.HOHL_ADA_SEG3);
            this.add(CalamityPartsHandeling.HOHL_ADA_TAIL);
         }
      };
   }

   public static record Part(int id, List<ModelPart> parts, float x, float y, float z, float xRot, float yRot, float zRot, ResourceLocation location, ResourceLocation adapted_location) {
   }
}
