/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Harbinger_Spore_Core_agents_transformers_SporeClassFileTransformer0 */

#ifndef _Included_com_Harbinger_Spore_Core_agents_transformers_SporeClassFileTransformer0
#define _Included_com_Harbinger_Spore_Core_agents_transformers_SporeClassFileTransformer0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Harbinger_Spore_Core_agents_transformers_SporeClassFileTransformer0
 * Method:    transform
 * Signature: (Ljava/lang/Module;Ljava/lang/ClassLoader;Ljava/lang/String;Ljava/lang/Class;Ljava/security/ProtectionDomain;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_Harbinger_Spore_Core_agents_transformers_SporeClassFileTransformer0_transform__Ljava_lang_Module_2Ljava_lang_ClassLoader_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_security_ProtectionDomain_2_3B
  (JNIEnv *, jobject, jobject, jobject, jstring, jclass, jobject, jbyteArray);

/*
 * Class:     com_Harbinger_Spore_Core_agents_transformers_SporeClassFileTransformer0
 * Method:    transform
 * Signature: (Ljava/lang/ClassLoader;Ljava/lang/String;Ljava/lang/Class;Ljava/security/ProtectionDomain;[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_Harbinger_Spore_Core_agents_transformers_SporeClassFileTransformer0_transform__Ljava_lang_ClassLoader_2Ljava_lang_String_2Ljava_lang_Class_2Ljava_security_ProtectionDomain_2_3B
  (JNIEnv *, jobject, jobject, jstring, jclass, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
